"""Tests for the Phase 9 submission export + validation pipeline.

There are three logical layers we want to protect here:

1. **Exporter unit tests** — the bundler deterministically collapses
   the live path into one string, respects the module order, strips
   internal imports, and handles both datamodel modes correctly.

2. **Validator unit tests** — the validator flags clearly-broken
   submissions (forbidden imports, missing Trader, residual src
   imports) and passes clean ones.

3. **End-to-end dry run** — with ``--datamodel=inline`` the bundled
   file is self-contained. We write it to ``tmp_path``, load it with
   ``importlib.util.spec_from_file_location`` (carefully registering
   the module in ``sys.modules`` so dataclass decorators can resolve
   their own class ``__module__``), instantiate ``Trader``, and run
   it on a minimal ``TradingState``. This is the strict
   proof-by-execution that replaces the old 30-line stub.

The dry-run test deliberately avoids any reliance on ``src/``. If you
accidentally break the bundler, these tests fail loudly.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import types
from pathlib import Path

import pytest

from src.scripts.export_submission import (
    DATAMODEL_PATH,
    DEFAULT_OUTPUT,
    EXPORT_PROFILES,
    LIVE_MODULE_ORDER,
    R3_MODULE_ORDER,
    ExportOptions,
    build_submission_source,
    strip_module,
    verify_live_module_order,
    write_submission,
)
from src.scripts.validate_submission import (
    MAX_SIZE_BYTES,
    SOFT_SIZE_BYTES,
    validate_file,
    validate_source,
)

REPO_ROOT = Path(__file__).resolve().parents[1]


# -------------------------------------------------------------- exporter


@pytest.mark.unit
def test_strip_module_removes_future_and_src_imports() -> None:
    source = (
        '"""docstring."""\n'
        "from __future__ import annotations\n"
        "\n"
        "import math\n"
        "from src.core.types import NormalizedSnapshot\n"
        "from src.datamodel import Order\n"
        "\n"
        "def f() -> int:\n"
        "    return 1\n"
    )
    stripped = strip_module("fake/mod.py", source)

    assert "from __future__" not in stripped.body
    assert "from src." not in stripped.body
    assert "import math" not in stripped.body  # hoisted, not in body
    assert "def f() -> int" in stripped.body
    assert '"""docstring."""' in stripped.body

    assert any("import math" in imp for imp in stripped.hoisted_imports)
    assert stripped.datamodel_symbols == {"Order"}


@pytest.mark.unit
def test_strip_module_hoists_multiline_imports() -> None:
    source = (
        "from __future__ import annotations\n"
        "from collections.abc import (\n"
        "    Mapping,\n"
        "    Sequence,\n"
        ")\n"
        "x = 1\n"
    )
    stripped = strip_module("fake/multiline.py", source)
    joined = "\n".join(stripped.hoisted_imports)
    assert "Mapping" in joined
    assert "Sequence" in joined
    assert "x = 1" in stripped.body


@pytest.mark.unit
def test_build_submission_platform_mode_emits_datamodel_header() -> None:
    bundle = build_submission_source(ExportOptions(datamodel_mode="platform"))
    source = bundle.source

    assert source.startswith("# Auto-generated by src/scripts/export_submission.py")
    assert "from __future__ import annotations" in source
    assert "from datamodel import " in source
    # Every live module must appear as a banner in the bundled file.
    for module_path in LIVE_MODULE_ORDER:
        assert f"# {module_path}" in source
    # The inline datamodel path must NOT appear as its own banner
    # (platform mode relies on the container-provided datamodel).
    assert f"# {DATAMODEL_PATH}" not in source
    assert bundle.datamodel_mode == "platform"
    assert bundle.module_count == len(LIVE_MODULE_ORDER)
    assert bundle.datamodel_symbols  # non-empty


@pytest.mark.unit
def test_build_submission_inline_mode_embeds_datamodel() -> None:
    bundle = build_submission_source(ExportOptions(datamodel_mode="inline"))
    source = bundle.source

    assert "from datamodel import " not in source
    assert f"# {DATAMODEL_PATH}" in source
    # Sanity: symbols defined in datamodel appear in the body.
    assert "class TradingState" in source
    assert "class Order" in source
    assert bundle.datamodel_mode == "inline"
    assert bundle.module_count == len(LIVE_MODULE_ORDER) + 1


@pytest.mark.unit
def test_build_submission_bundle_has_no_residual_src_imports() -> None:
    for mode in ("platform", "inline"):
        bundle = build_submission_source(ExportOptions(datamodel_mode=mode))
        assert "from src." not in bundle.source, f"{mode} mode leaked src import"
        assert "import src." not in bundle.source, f"{mode} mode leaked src import"


@pytest.mark.unit
def test_build_submission_is_deterministic() -> None:
    a = build_submission_source(ExportOptions(datamodel_mode="platform")).source
    b = build_submission_source(ExportOptions(datamodel_mode="platform")).source
    assert a == b


@pytest.mark.unit
def test_invalid_datamodel_mode_raises() -> None:
    with pytest.raises(ValueError):
        ExportOptions(datamodel_mode="hybrid")


@pytest.mark.unit
def test_write_submission_creates_parent_dirs(tmp_path: Path) -> None:
    bundle = build_submission_source(ExportOptions(datamodel_mode="inline"))
    target = tmp_path / "nested" / "dir" / "bundle.py"
    written = write_submission(bundle, target)
    assert written.exists()
    assert written.read_text(encoding="utf-8") == bundle.source


# -------------------------------------------------------------- validator


def _make_bundle_source(mode: str = "platform") -> str:
    return build_submission_source(ExportOptions(datamodel_mode=mode)).source


@pytest.mark.unit
def test_validator_passes_clean_bundle() -> None:
    source = _make_bundle_source("platform")
    report = validate_source(source)
    assert report.ok, report.format()
    assert report.errors == []


@pytest.mark.unit
def test_validator_flags_forbidden_import() -> None:
    bad = "import requests\nclass Trader:\n    def run(self, s):\n        return {}, 0, ''\n"
    report = validate_source(bad)
    codes = {issue.code for issue in report.errors}
    assert "forbidden_import" in codes


@pytest.mark.unit
def test_validator_flags_residual_src_import() -> None:
    bad = (
        "from src.core.config import EngineConfig\n"
        "class Trader:\n"
        "    def run(self, s):\n"
        "        return {}, 0, ''\n"
    )
    report = validate_source(bad)
    codes = {issue.code for issue in report.errors}
    assert "residual_src_import" in codes


@pytest.mark.unit
def test_validator_flags_dev_only_import() -> None:
    bad = (
        "from src.backtest.simulator import BacktestSimulator\n"
        "class Trader:\n"
        "    def run(self, s):\n"
        "        return {}, 0, ''\n"
    )
    report = validate_source(bad)
    codes = {issue.code for issue in report.errors}
    assert "dev_only_import" in codes


@pytest.mark.unit
def test_validator_requires_trader_class() -> None:
    bad = "x = 1\n"
    report = validate_source(bad)
    codes = {issue.code for issue in report.errors}
    assert "missing_trader" in codes


@pytest.mark.unit
def test_validator_requires_run_method() -> None:
    bad = "class Trader:\n    pass\n"
    report = validate_source(bad)
    codes = {issue.code for issue in report.errors}
    assert "missing_run" in codes


@pytest.mark.unit
def test_validator_flags_bare_open_call() -> None:
    bad = (
        "class Trader:\n"
        "    def run(self, s):\n"
        "        open('/tmp/x', 'w')\n"
        "        return {}, 0, ''\n"
    )
    report = validate_source(bad)
    codes = {issue.code for issue in report.errors}
    assert "file_io_open" in codes


@pytest.mark.unit
def test_validator_warns_on_print() -> None:
    source = (
        "class Trader:\n"
        "    def run(self, s):\n"
        "        print('debug')\n"
        "        return {}, 0, ''\n"
    )
    report = validate_source(source)
    warn_codes = {issue.code for issue in report.warnings}
    assert "debug_print" in warn_codes
    # No error-level issues from the print alone.
    assert not any(issue.code == "debug_print" for issue in report.errors)


@pytest.mark.unit
def test_validator_rejects_oversize_bundle() -> None:
    padding = "#" * (MAX_SIZE_BYTES + 100)
    source = (
        f"# {padding}\n" "class Trader:\n" "    def run(self, s):\n" "        return {}, 0, ''\n"
    )
    report = validate_source(source)
    codes = {issue.code for issue in report.errors}
    assert "oversize" in codes


@pytest.mark.unit
def test_validator_file_missing_returns_error(tmp_path: Path) -> None:
    report = validate_file(tmp_path / "does_not_exist.py")
    assert not report.ok
    assert any(issue.code == "missing_file" for issue in report.errors)


# ------------------------------------------------------------- smoke test


def _load_bundle_module(path: Path, name: str) -> types.ModuleType:
    """Import a bundled submission file in isolation.

    The ``sys.modules`` registration before ``exec_module`` is
    required on Python >= 3.14: the stdlib ``dataclasses`` decorator
    looks up ``cls.__module__`` in ``sys.modules`` to compute type
    annotations, and raises ``AttributeError`` if the module hasn't
    been registered yet.
    """
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        sys.modules.pop(name, None)
        raise
    return module


def _empty_trading_state(module: types.ModuleType) -> object:
    return module.TradingState(
        traderData="",
        timestamp=0,
        listings={},
        order_depths={},
        own_trades={},
        market_trades={},
        position={},
        observations=module.Observation(),
    )


def _emeralds_state(
    module: types.ModuleType,
    *,
    trader_data: str = "",
    timestamp: int = 0,
) -> object:
    """Build a ``TradingState`` with a minimal EMERALDS order book.

    EMERALDS is pinned around 10,000 by the default engine config, so
    a book straddling 10,000 is guaranteed to produce a mid and drive
    the market-making strategy to update ``recent_mids`` — which is
    what the round-trip smoke test asserts.
    """
    depth = module.OrderDepth(
        buy_orders={9998: 5, 9997: 10},
        sell_orders={10002: -5, 10003: -10},
    )
    return module.TradingState(
        traderData=trader_data,
        timestamp=timestamp,
        listings={},
        order_depths={"EMERALDS": depth},
        own_trades={},
        market_trades={},
        position={},
        observations=module.Observation(),
    )


@pytest.mark.integration
def test_dry_run_inline_bundle_executes(tmp_path: Path) -> None:
    bundle = build_submission_source(ExportOptions(datamodel_mode="inline"))
    path = tmp_path / "trader_submission_inline.py"
    write_submission(bundle, path)

    module_name = "_phase9_smoke_inline"
    try:
        module = _load_bundle_module(path, module_name)

        assert hasattr(module, "Trader")
        assert hasattr(module, "TradingState")

        trader = module.Trader()
        state = _empty_trading_state(module)
        result = trader.run(state)

        assert isinstance(result, tuple)
        assert len(result) == 3
        orders, conversions, trader_data = result
        assert isinstance(orders, dict)
        assert isinstance(conversions, int)
        assert isinstance(trader_data, str)
    finally:
        sys.modules.pop(module_name, None)


@pytest.mark.integration
def test_dry_run_platform_bundle_imports_with_injected_datamodel(
    tmp_path: Path,
) -> None:
    """Platform mode file loads when ``datamodel`` is injected.

    This proves the exporter emits a valid ``from datamodel import
    ...`` header and the rest of the bundle parses against the real
    Prosperity datamodel contract (which we mirror in
    ``src/datamodel.py``).
    """
    bundle = build_submission_source(ExportOptions(datamodel_mode="platform"))
    path = tmp_path / "trader_submission_platform.py"
    write_submission(bundle, path)

    # Inject our local mirror as the platform-provided ``datamodel``
    # module for the duration of the load.
    import src.datamodel as local_datamodel

    sentinel = sys.modules.get("datamodel")
    sys.modules["datamodel"] = local_datamodel
    module_name = "_phase9_smoke_platform"
    try:
        module = _load_bundle_module(path, module_name)
        trader = module.Trader()
        state = _empty_trading_state(local_datamodel)
        result = trader.run(state)
        assert len(result) == 3
    finally:
        sys.modules.pop(module_name, None)
        if sentinel is None:
            sys.modules.pop("datamodel", None)
        else:
            sys.modules["datamodel"] = sentinel


@pytest.mark.integration
def test_default_output_path_is_under_outputs_submissions() -> None:
    # Static guard: any change to the default must keep it under
    # outputs/submissions/ so downstream tooling can rely on it.
    assert DEFAULT_OUTPUT.parent.name == "submissions"
    assert DEFAULT_OUTPUT.parent.parent.name == "outputs"
    assert DEFAULT_OUTPUT.name.endswith(".py")


@pytest.mark.integration
def test_dry_run_state_round_trips_across_two_calls(tmp_path: Path) -> None:
    """Two sequential ``Trader.run()`` calls with traderData flowing.

    This proves three things about the bundled artifact:

    1. The bundled ``Trader`` instantiates.
    2. ``StateStore`` inside the bundle can parse its own output on
       the next call (schema round-trip inside the exported file).
    3. Per-product memory actually grows across iterations (so
       ``ProductMemory.recent_mids`` is really being persisted
       through ``traderData``, not just reset on every call).

    A one-shot smoke is not enough here: it would miss any bug where
    the exporter accidentally breaks the state-store parse/serialize
    cycle.
    """
    bundle = build_submission_source(ExportOptions(datamodel_mode="inline"))
    path = tmp_path / "trader_submission_roundtrip.py"
    write_submission(bundle, path)

    module_name = "_phase9_smoke_round_trip"
    try:
        module = _load_bundle_module(path, module_name)
        trader = module.Trader()

        state1 = _emeralds_state(module, timestamp=0)
        _, _, trader_data1 = trader.run(state1)
        assert isinstance(trader_data1, str) and trader_data1
        parsed1 = json.loads(trader_data1)
        assert parsed1.get("version") == 1
        mids1 = parsed1["products"]["EMERALDS"]["recent_mids"]
        assert len(mids1) == 1, "first iteration should append one mid"

        # Feed the returned traderData back in and run again.
        state2 = _emeralds_state(module, trader_data=trader_data1, timestamp=100)
        _, _, trader_data2 = trader.run(state2)
        parsed2 = json.loads(trader_data2)
        mids2 = parsed2["products"]["EMERALDS"]["recent_mids"]
        assert len(mids2) == 2, (
            "second iteration should append another mid, proving "
            "traderData round-tripped through the bundled StateStore"
        )
        # The first value must be preserved.
        assert mids2[0] == pytest.approx(mids1[0])
    finally:
        sys.modules.pop(module_name, None)


# ------------------------------------------------------- completeness check


@pytest.mark.unit
def test_verify_live_module_order_accepts_current_live_path() -> None:
    # This is the active guard: if someone removes a file from
    # LIVE_MODULE_ORDER that the rest of the live path still depends
    # on, this call raises before the exporter can produce a broken
    # bundle.
    verify_live_module_order(list(LIVE_MODULE_ORDER), root=REPO_ROOT)


@pytest.mark.unit
def test_verify_live_module_order_detects_missing_module(
    tmp_path: Path,
) -> None:
    """Simulate a live module that imports something not in the order list.

    We build a tiny fake repo under ``tmp_path`` with two modules:
    ``src/core/entry.py`` imports ``src.core.dep``, but we only pass
    ``entry.py`` to the verifier. The verifier must raise a
    RuntimeError that mentions the missing target.
    """
    fake_root = tmp_path / "fake_repo"
    (fake_root / "src" / "core").mkdir(parents=True)
    (fake_root / "src" / "__init__.py").write_text("")
    (fake_root / "src" / "core" / "__init__.py").write_text("")
    (fake_root / "src" / "datamodel.py").write_text("class TradingState: ...\n")
    (fake_root / "src" / "core" / "entry.py").write_text(
        "from src.core.dep import helper\n" "def run():\n" "    return helper()\n"
    )
    (fake_root / "src" / "core" / "dep.py").write_text("def helper():\n    return 1\n")

    with pytest.raises(RuntimeError) as excinfo:
        verify_live_module_order(["src/core/entry.py"], root=fake_root)

    message = str(excinfo.value)
    assert "src.core.dep" in message
    assert "LIVE_MODULE_ORDER" in message


@pytest.mark.unit
def test_verify_live_module_order_flags_unresolved_imports(
    tmp_path: Path,
) -> None:
    """A dangling ``from src.x import y`` with no file on disk is an error."""
    fake_root = tmp_path / "fake_repo"
    (fake_root / "src").mkdir(parents=True)
    (fake_root / "src" / "__init__.py").write_text("")
    (fake_root / "src" / "datamodel.py").write_text("class TradingState: ...\n")
    (fake_root / "src" / "entry.py").write_text("from src.nonexistent_module import whatever\n")

    with pytest.raises(RuntimeError) as excinfo:
        verify_live_module_order(["src/entry.py"], root=fake_root)
    assert "src.nonexistent_module" in str(excinfo.value)


# ----------------------------------------------------- size budget + dev-only


@pytest.mark.unit
def test_validator_soft_size_emits_warning() -> None:
    assert SOFT_SIZE_BYTES < MAX_SIZE_BYTES
    # Craft a bundle just over the soft threshold but well under the
    # hard one. We pad with a harmless comment so the file still
    # parses and still has a valid Trader class.
    pad_bytes = SOFT_SIZE_BYTES + 500
    padding = "# " + ("x" * (pad_bytes - 2)) + "\n"
    source = padding + "class Trader:\n" + "    def run(self, s):\n" + "        return {}, 0, ''\n"
    assert SOFT_SIZE_BYTES < len(source.encode("utf-8")) < MAX_SIZE_BYTES

    report = validate_source(source)
    warn_codes = {issue.code for issue in report.warnings}
    assert "size_approaching_limit" in warn_codes
    # Soft breach must not fail the gate.
    assert report.ok


@pytest.mark.unit
def test_validator_report_header_prints_both_thresholds() -> None:
    source = "class Trader:\n    def run(self, s):\n        return {}, 0, ''\n"
    report = validate_source(source)
    rendered = report.format()
    assert "soft" in rendered
    assert "hard" in rendered
    assert str(SOFT_SIZE_BYTES) in rendered
    assert str(MAX_SIZE_BYTES) in rendered


@pytest.mark.unit
def test_validator_warns_on_inline_datamodel_bundle() -> None:
    bundle = build_submission_source(ExportOptions(datamodel_mode="inline"))
    report = validate_source(bundle.source)
    warn_codes = {issue.code for issue in report.warnings}
    assert "inline_datamodel_dev_only" in warn_codes
    # Inline bundle still passes structurally — it just carries the
    # loud warning that it is dev-only.
    assert report.ok


@pytest.mark.unit
def test_validator_platform_bundle_has_no_inline_warning() -> None:
    bundle = build_submission_source(ExportOptions(datamodel_mode="platform"))
    report = validate_source(bundle.source)
    warn_codes = {issue.code for issue in report.warnings}
    assert "inline_datamodel_dev_only" not in warn_codes


# ============================================================ R3 profile


@pytest.mark.unit
def test_export_profiles_enumerate_expected_values() -> None:
    assert set(EXPORT_PROFILES) == {"r2", "r3"}


@pytest.mark.unit
def test_r3_profile_replaces_r1_r2_only_modules() -> None:
    """R3 keeps the core R2 modules an orchestrator-driven Trader needs
    and drops the R1/R2-only modules (config product factories,
    FairValueEngine, per-product strategies). Locks in the size trim
    so an accidental re-add surfaces in review."""
    r3_set = set(R3_MODULE_ORDER)
    # Modules R3 must still carry (anything the Trader touches
    # unconditionally or through orchestrator).
    mandatory = {
        "src/core/utils.py",
        "src/core/types.py",
        "src/core/config_core.py",
        "src/core/market_data.py",
        "src/core/state_store.py",
        "src/core/execution.py",
        "src/core/risk.py",
        "src/core/residual.py",
        "src/core/signals.py",
        "src/signals/flow_analyzer.py",
        "src/trader.py",
    }
    missing = mandatory - r3_set
    assert not missing, f"R3 bundle missing mandatory R2 modules: {missing}"
    # Modules R3 deliberately drops (ship with extra_modules per
    # submission if a given R3 engine needs them).
    dropped = {
        "src/core/config.py",
        "src/core/fair_value.py",
        "src/strategies/base.py",
        "src/strategies/market_making.py",
        "src/strategies/buy_and_hold.py",
        "src/strategies/__init__.py",
    }
    accidentally_kept = dropped & r3_set
    assert not accidentally_kept, (
        f"R3 bundle retained R1/R2-only modules: {accidentally_kept}"
    )


@pytest.mark.unit
def test_r3_profile_includes_orchestrator_primitives() -> None:
    """Any orchestrator-enabled submission needs these 3 modules at minimum."""
    required = {
        "src/core/primitives/engine_orchestrator.py",
        "src/core/primitives/portfolio_context.py",
        "src/conversions/adapter.py",
    }
    missing = required - set(R3_MODULE_ORDER)
    assert not missing, f"R3 profile missing required modules: {missing}"


@pytest.mark.unit
def test_r3_profile_places_trader_last() -> None:
    """trader.py must be the last module so every dependency is defined
    before Trader's bundled body references them."""
    assert R3_MODULE_ORDER[-1] == "src/trader.py"


@pytest.mark.unit
def test_r3_bundle_has_no_residual_src_imports() -> None:
    bundle = build_submission_source(
        ExportOptions(datamodel_mode="platform", profile="r3"),
    )
    assert "from src." not in bundle.source, "R3 bundle leaked src import"
    assert "import src." not in bundle.source, "R3 bundle leaked src import"
    assert bundle.module_count == len(R3_MODULE_ORDER)


@pytest.mark.unit
def test_r3_bundle_is_deterministic() -> None:
    a = build_submission_source(
        ExportOptions(datamodel_mode="platform", profile="r3"),
    ).source
    b = build_submission_source(
        ExportOptions(datamodel_mode="platform", profile="r3"),
    ).source
    assert a == b


@pytest.mark.unit
def test_r3_bundle_size_is_tracked() -> None:
    """Track the core-R3 bundle size so growth is visible in diffs.

    The R2 base bundle already sits at ~117 KB (near the self-imposed
    120 KB soft cap and the Prosperity ~128 KB platform ceiling). The
    R3 profile layers cross-product primitives on top — current size
    is ~163 KB. This exceeds the platform cap and will require trimming
    ``src/core/config.py`` (30 KB of R1/R2 product factories) before an
    R3 submission can actually ship. This test does not fail on the
    overage; it captures the floor + ceiling so the next regression
    review surfaces any further growth.
    """
    bundle = build_submission_source(
        ExportOptions(datamodel_mode="platform", profile="r3"),
    )
    # Floor: R3 must weigh more than bare R2 (otherwise the profile
    # isn't actually pulling in its additional modules).
    r2 = build_submission_source(
        ExportOptions(datamodel_mode="platform", profile="r2"),
    )
    assert bundle.size_bytes > r2.size_bytes, (
        "R3 bundle did not grow relative to R2 — profile not wired"
    )
    # Ceiling: alarm if we somehow balloon past 200 KB — at that point
    # the trimming plan has been deferred too long.
    assert bundle.size_bytes < 200 * 1024, (
        f"R3 bundle has grown to {bundle.size_bytes}B; trim before shipping"
    )


@pytest.mark.unit
def test_extra_modules_appended_to_profile() -> None:
    """``extra_modules`` adds per-submission opt-in engines."""
    bundle = build_submission_source(ExportOptions(
        datamodel_mode="platform",
        profile="r3",
        extra_modules=("src/options/bsm.py",),
    ))
    assert bundle.module_count == len(R3_MODULE_ORDER) + 1
    assert "# src/options/bsm.py" in bundle.source


@pytest.mark.unit
def test_extra_modules_dedupe_against_profile() -> None:
    """Passing an extra already present in the profile is a no-op."""
    # portfolio_context is already in R3_MODULE_ORDER.
    bundle = build_submission_source(ExportOptions(
        datamodel_mode="platform",
        profile="r3",
        extra_modules=("src/core/primitives/portfolio_context.py",),
    ))
    assert bundle.module_count == len(R3_MODULE_ORDER)


@pytest.mark.unit
def test_invalid_profile_raises() -> None:
    with pytest.raises(ValueError, match="profile"):
        ExportOptions(profile="r99")


@pytest.mark.integration
def test_dry_run_r3_bundle_executes_with_orchestrator(tmp_path: Path) -> None:
    """R3 inline bundle boots and runs Trader.run(...) with an
    EngineOrchestrator passed in. Proves the bundled primitives +
    orchestrator + conversion adapter wire up end-to-end."""
    bundle = build_submission_source(
        ExportOptions(datamodel_mode="inline", profile="r3"),
    )
    path = tmp_path / "trader_submission_r3.py"
    write_submission(bundle, path)

    module_name = "_r3_smoke"
    try:
        module = _load_bundle_module(path, module_name)
        assert hasattr(module, "Trader")
        assert hasattr(module, "EngineOrchestrator")
        assert hasattr(module, "build_portfolio_snapshot")
        assert hasattr(module, "extract_remote_quotes")

        # Build an empty orchestrator (engines are opt-in via extra_modules).
        orch = module.EngineOrchestrator(engines=[])
        # R3 bundles drop the ``default_engine_config`` factory; an R3
        # submission must supply its own EngineConfig. An empty one is
        # fine for the dry run — we just want to prove the chain executes.
        empty_config = module.EngineConfig(products={})
        trader = module.Trader(config=empty_config, orchestrator=orch)
        state = _empty_trading_state(module)
        orders, conversions, trader_data = trader.run(state)

        assert isinstance(orders, dict)
        assert isinstance(conversions, int)
        assert isinstance(trader_data, str)
    finally:
        sys.modules.pop(module_name, None)
