# Auto-generated by src/scripts/export_submission.py. DO NOT EDIT.
# Datamodel mode: inline.
# Source modules: 15.

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, is_dataclass
from json import JSONEncoder
from typing import Any
from collections.abc import Sequence
from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Literal
from typing import Protocol
import warnings
from dataclasses import asdict
import math
from dataclasses import dataclass
from abc import ABC, abstractmethod
from collections.abc import Callable, Mapping
import logging

# ========================================================================
# src/datamodel.py
# ========================================================================

"""Local mirror of the Prosperity ``datamodel`` module.

The IMC Prosperity runtime imports ``datamodel`` from the execution
environment. This file mirrors that contract exactly so that locally
developed code is type- and shape-compatible with the upload target.

Rules:
- Do not add strategy logic here.
- Do not rename or retype fields without a matching change in the
  submission packaging step.
- Keep field names identical to the platform (``buy_orders``,
  ``sell_orders``, ``order_depths``, etc.).
- Sell orders on Prosperity use *negative* volumes by convention; we
  preserve that convention here and normalize it in ``core.market_data``.
"""



Time = int
Symbol = str
Product = str
Position = int
UserId = str


@dataclass
class Listing:
    symbol: Symbol
    product: Product
    denomination: Product


@dataclass
class ConversionObservation:
    bidPrice: float
    askPrice: float
    transportFees: float
    exportTariff: float
    importTariff: float
    sunlight: float
    humidity: float


@dataclass
class Observation:
    plainValueObservations: dict[Product, int] = field(default_factory=dict)
    conversionObservations: dict[Product, ConversionObservation] = field(default_factory=dict)


@dataclass
class Order:
    symbol: Symbol
    price: int
    quantity: int


@dataclass
class OrderDepth:
    buy_orders: dict[int, int] = field(default_factory=dict)
    sell_orders: dict[int, int] = field(default_factory=dict)


@dataclass
class Trade:
    symbol: Symbol
    price: int
    quantity: int
    buyer: UserId | None = None
    seller: UserId | None = None
    timestamp: int = 0


@dataclass
class TradingState:
    traderData: str
    timestamp: Time
    listings: dict[Symbol, Listing]
    order_depths: dict[Symbol, OrderDepth]
    own_trades: dict[Symbol, list[Trade]]
    market_trades: dict[Symbol, list[Trade]]
    position: dict[Product, Position]
    observations: Observation

    def to_json(self) -> str:
        return json.dumps(self, cls=ProsperityEncoder, sort_keys=True)


class ProsperityEncoder(JSONEncoder):
    def default(self, value: Any) -> Any:
        if is_dataclass(value) and not isinstance(value, type):
            return asdict(value)
        if hasattr(value, "__dict__"):
            return value.__dict__
        return super().default(value)

# ========================================================================
# src/core/utils.py
# ========================================================================

def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(value, high))


def bounded_append(values: list[float], value: float, maxlen: int) -> None:
    values.append(value)
    if len(values) > maxlen:
        del values[: len(values) - maxlen]


def weighted_average(values: Sequence[float], weights: Sequence[float]) -> float:
    if len(values) != len(weights):
        raise ValueError("values and weights must have the same length")
    total_weight = float(sum(weights))
    if total_weight == 0:
        raise ValueError("weights must not sum to zero")
    return sum(value * weight for value, weight in zip(values, weights, strict=True)) / total_weight

# ========================================================================
# src/core/types.py
# ========================================================================

"""Shared engine types.

These types are the stable vocabulary spoken by every engine layer:
fair value, signals, execution, risk, and strategies.

Design notes:
- ``NormalizedSnapshot`` is frozen. Downstream code should not mutate it.
- ``ProductMemory`` is mutable because it is the authoritative rolling state
  we persist through ``traderData``; mutation is explicit and local.
- ``FairValueEstimate`` and ``SignalIntent`` are frozen so strategy code
  cannot accidentally mutate outputs of the fair value or signal stages.
  Their container fields (``components``, ``metadata``) are typed as
  ``Mapping`` and default to ``MappingProxyType({})`` so mutation is
  rejected at runtime as well as discouraged by the type system.
"""



Product = str
Timestamp = int
Scalar = int | float | str | bool
ExecutionMode = Literal["idle", "maker", "taker", "recovery", "hybrid"]


def _empty_scalar_map() -> Mapping[str, Scalar]:
    return MappingProxyType({})


@dataclass(frozen=True)
class BookLevel:
    price: int
    volume: int


@dataclass(frozen=True)
class TradePrint:
    price: int
    quantity: int
    buyer: str | None = None
    seller: str | None = None
    timestamp: int = 0
    source: Literal["own", "market"] = "market"


@dataclass(frozen=True)
class NormalizedSnapshot:
    product: Product
    timestamp: Timestamp
    bids: tuple[BookLevel, ...] = ()
    asks: tuple[BookLevel, ...] = ()
    position: int = 0
    trades: tuple[TradePrint, ...] = ()

    @property
    def best_bid(self) -> BookLevel | None:
        return self.bids[0] if self.bids else None

    @property
    def best_ask(self) -> BookLevel | None:
        return self.asks[0] if self.asks else None

    @property
    def mid(self) -> float | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return (self.best_bid.price + self.best_ask.price) / 2.0

    @property
    def spread(self) -> float | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return float(self.best_ask.price - self.best_bid.price)

    @property
    def book_imbalance(self) -> float | None:
        """Top-of-book imbalance in [-1, 1], positive = bid-heavy."""
        if self.best_bid is None or self.best_ask is None:
            return None
        total = self.best_bid.volume + self.best_ask.volume
        if total <= 0:
            return None
        return (self.best_bid.volume - self.best_ask.volume) / total

    @property
    def microprice(self) -> float | None:
        """Volume-weighted best price, i.e. mid tilted toward the thicker side."""
        if self.best_bid is None or self.best_ask is None:
            return None
        total = self.best_bid.volume + self.best_ask.volume
        if total <= 0:
            return None
        return (
            (self.best_bid.price * self.best_ask.volume)
            + (self.best_ask.price * self.best_bid.volume)
        ) / total

    def total_bid_volume(self, depth: int | None = None) -> int:
        levels = self.bids if depth is None else self.bids[:depth]
        return sum(level.volume for level in levels)

    def total_ask_volume(self, depth: int | None = None) -> int:
        levels = self.asks if depth is None else self.asks[:depth]
        return sum(level.volume for level in levels)

    def top_bids(self, depth: int) -> tuple[BookLevel, ...]:
        if depth <= 0:
            return ()
        return self.bids[:depth]

    def top_asks(self, depth: int) -> tuple[BookLevel, ...]:
        if depth <= 0:
            return ()
        return self.asks[:depth]


@dataclass
class ProductMemory:
    recent_mids: list[float] = field(default_factory=list)
    recent_spreads: list[float] = field(default_factory=list)
    counters: dict[str, int] = field(default_factory=dict)
    flags: dict[str, bool] = field(default_factory=dict)
    values: dict[str, float] = field(default_factory=dict)


@dataclass
class EngineState:
    version: int = 1
    products: dict[Product, ProductMemory] = field(default_factory=dict)

    def for_product(self, product: Product) -> ProductMemory:
        memory = self.products.get(product)
        if memory is None:
            memory = ProductMemory()
            self.products[product] = memory
        return memory


@dataclass(frozen=True)
class FairValueEstimate:
    price: float
    method: str
    confidence: float | None = None
    components: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)


@dataclass(frozen=True)
class QuoteIntent:
    bid_price: int | None = None
    bid_size: int = 0
    ask_price: int | None = None
    ask_size: int = 0


@dataclass(frozen=True)
class SignalIntent:
    product: Product
    fair_value: FairValueEstimate
    mode: ExecutionMode = "idle"
    buy_below: float | None = None
    sell_above: float | None = None
    quote: QuoteIntent | None = None
    rationale: str = ""
    metadata: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)

# ========================================================================
# src/core/config.py
# ========================================================================

"""Engine and per-product configuration.

``ProductConfig`` is a frozen dataclass that binds every tunable knob for
one product. ``EngineConfig`` bundles a set of product configs with
runtime-wide knobs such as the state store version and the trader data
char budget.

Fair value resolution:

- ``fair_value_method`` names the primary estimator.
- ``fair_value_fallbacks`` is an ordered tuple of estimator names that
  will be tried in turn if the primary returns ``None`` (missing data,
  insufficient history, etc.). The doctrine requires a fallback path to
  always exist; this is where it lives.

Validation happens at construction time so misconfigured runs fail
immediately instead of producing subtle bad behavior deep inside the
live loop.
"""




@dataclass(frozen=True)
class ProductConfig:
    position_limit: int
    strategy_name: str
    fair_value_method: str
    fair_value_fallbacks: tuple[str, ...] = ()
    tick_size: int = 1
    anchor_price: float | None = None
    taker_edge: float = 1.0
    maker_edge: float = 1.0
    quote_size: int = 5
    max_aggressive_size: int = 10
    inventory_skew: float = 2.0
    flatten_threshold: float = 0.8
    history_length: int = 32

    def __post_init__(self) -> None:
        if self.position_limit <= 0:
            raise ValueError(
                f"ProductConfig.position_limit must be > 0 (got {self.position_limit})"
            )
        if self.tick_size <= 0:
            raise ValueError(f"ProductConfig.tick_size must be > 0 (got {self.tick_size})")
        if self.quote_size < 0:
            raise ValueError(f"ProductConfig.quote_size must be >= 0 (got {self.quote_size})")
        if self.max_aggressive_size < 0:
            raise ValueError(
                f"ProductConfig.max_aggressive_size must be >= 0 "
                f"(got {self.max_aggressive_size})"
            )
        if self.taker_edge < 0 or self.maker_edge < 0:
            raise ValueError("ProductConfig.*_edge must be >= 0")
        if self.inventory_skew < 0:
            raise ValueError("ProductConfig.inventory_skew must be >= 0")
        if not 0.0 <= self.flatten_threshold <= 1.0:
            raise ValueError(
                f"ProductConfig.flatten_threshold must be in [0, 1] "
                f"(got {self.flatten_threshold})"
            )
        if self.history_length < 0:
            raise ValueError("ProductConfig.history_length must be >= 0")
        if self.fair_value_method == "anchor" and self.anchor_price is None:
            raise ValueError("ProductConfig: fair_value_method='anchor' requires anchor_price")


@dataclass(frozen=True)
class EngineConfig:
    state_version: int = 1
    max_trader_data_chars: int = 50_000
    diagnostics_verbosity: int = 1
    products: dict[str, ProductConfig] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.state_version < 1:
            raise ValueError("EngineConfig.state_version must be >= 1")
        if self.max_trader_data_chars <= 0:
            raise ValueError("EngineConfig.max_trader_data_chars must be > 0")

    def product_config(self, product: str) -> ProductConfig | None:
        return self.products.get(product)


def default_engine_config() -> EngineConfig:
    # Both tutorial products use the shared market-making strategy, differing
    # only by their fair-value choice. maker_edge is kept at a principled 2
    # (tick beyond the anchor) rather than the data-fit value of 8 we briefly
    # used to chase the tutorial trade tape. See docs/eda_tutorial_round_1.md
    # for why the tutorial replay under-rewards inside-spread makers.
    return EngineConfig(
        products={
            "EMERALDS": ProductConfig(
                position_limit=20,
                strategy_name="market_making",
                fair_value_method="anchor",
                fair_value_fallbacks=("microprice", "mid"),
                anchor_price=10_000.0,
                taker_edge=1.0,
                maker_edge=2.0,
                quote_size=5,
                max_aggressive_size=10,
                inventory_skew=2.0,
                flatten_threshold=0.75,
                history_length=32,
            ),
            "TOMATOES": ProductConfig(
                position_limit=20,
                strategy_name="market_making",
                fair_value_method="weighted_mid",
                fair_value_fallbacks=("mid", "microprice"),
                taker_edge=1.0,
                maker_edge=1.0,
                quote_size=4,
                max_aggressive_size=8,
                inventory_skew=3.0,
                flatten_threshold=0.7,
                history_length=48,
            ),
        }
    )

# ========================================================================
# src/core/logger.py
# ========================================================================

class DecisionLogger:
    def __init__(self, max_events: int = 256) -> None:
        self.max_events = max_events
        self.events: list[dict[str, object]] = []

    def record(self, event: dict[str, object]) -> None:
        self.events.append(event)
        if len(self.events) > self.max_events:
            del self.events[: len(self.events) - self.max_events]

    def to_json(self, max_chars: int = 4_000) -> str:
        payload = json.dumps(self.events, separators=(",", ":"), sort_keys=True)
        if len(payload) <= max_chars:
            return payload
        return payload[: max_chars - 3] + "..."

# ========================================================================
# src/core/market_data.py
# ========================================================================

"""Raw ``TradingState`` -> canonical ``NormalizedSnapshot`` adapter.

Everything downstream of this module consumes ``NormalizedSnapshot``s, so
this is the only place that has to know how Prosperity lays out raw
order-book and trade data.

Conventions enforced here:

- Bids are sorted price-descending; asks are sorted price-ascending.
  Strategies can then rely on ``bids[0]`` being the best bid.
- Ask volumes are always returned as *positive* integers, regardless of
  whether the raw ``sell_orders`` dict uses Prosperity's negative-volume
  convention or an already-positive mirror. Zero-volume levels are
  dropped.
- Trade lists combine own and market trades and are sorted by timestamp,
  with a ``source`` tag preserved so diagnostics can distinguish them.

This module produces no orders and holds no state.
"""




class MarketDataAdapter:
    def normalize_state(self, state: TradingState) -> dict[str, NormalizedSnapshot]:
        snapshots: dict[str, NormalizedSnapshot] = {}
        for product, order_depth in state.order_depths.items():
            bids, asks = self._normalize_depth(order_depth)
            trades = self._normalize_trades(
                state.own_trades.get(product, []) if state.own_trades else [],
                state.market_trades.get(product, []) if state.market_trades else [],
            )
            snapshots[product] = NormalizedSnapshot(
                product=product,
                timestamp=state.timestamp,
                bids=bids,
                asks=asks,
                position=state.position.get(product, 0) if state.position else 0,
                trades=trades,
            )
        return snapshots

    @staticmethod
    def _normalize_depth(
        order_depth: OrderDepth,
    ) -> tuple[tuple[BookLevel, ...], tuple[BookLevel, ...]]:
        buys = getattr(order_depth, "buy_orders", {}) or {}
        sells = getattr(order_depth, "sell_orders", {}) or {}

        bids = tuple(
            BookLevel(price=int(price), volume=int(volume))
            for price, volume in sorted(buys.items(), key=lambda item: item[0], reverse=True)
            if int(volume) > 0
        )
        # Prosperity convention: sell_orders use negative volume.
        # We accept either convention and always return positive volumes.
        asks = tuple(
            BookLevel(price=int(price), volume=abs(int(volume)))
            for price, volume in sorted(sells.items(), key=lambda item: item[0])
            if int(volume) != 0
        )
        return bids, asks

    @staticmethod
    def _normalize_trades(
        own_trades: list[Trade], market_trades: list[Trade]
    ) -> tuple[TradePrint, ...]:
        combined: list[TradePrint] = []
        combined.extend(
            TradePrint(
                price=int(trade.price),
                quantity=int(trade.quantity),
                buyer=trade.buyer,
                seller=trade.seller,
                timestamp=int(trade.timestamp),
                source="own",
            )
            for trade in own_trades or []
        )
        combined.extend(
            TradePrint(
                price=int(trade.price),
                quantity=int(trade.quantity),
                buyer=trade.buyer,
                seller=trade.seller,
                timestamp=int(trade.timestamp),
                source="market",
            )
            for trade in market_trades or []
        )
        combined.sort(key=lambda trade: trade.timestamp)
        return tuple(combined)

# ========================================================================
# src/core/fair_value.py
# ========================================================================

"""Fair value estimators and the engine that resolves them.

Doctrine:

- Every trading decision must flow through a fair-value abstraction.
- Estimators are pluggable objects implementing the ``Estimator``
  protocol. New estimators register into ``ESTIMATORS``.
- Per-product resolution uses a primary estimator plus an ordered
  fallback chain (``ProductConfig.fair_value_fallbacks``). The first
  estimator in the chain that returns a non-``None`` result wins.
- ``estimate_all`` runs every registered estimator on the same snapshot
  so Phase 3 experiments can compare proxies side-by-side without
  rewriting production code.

Each estimator is stateless with respect to the request: it reads the
frozen snapshot and the product's rolling memory, and returns a
``FairValueEstimate`` or ``None`` to indicate that it cannot score this
step.
"""





class Estimator(Protocol):
    name: str

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None: ...


class AnchorEstimator:
    name = "anchor"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        if config.anchor_price is None:
            return None
        return FairValueEstimate(
            price=float(config.anchor_price),
            method=self.name,
            confidence=1.0,
            components=MappingProxyType({"anchor_price": float(config.anchor_price)}),
        )


class MidEstimator:
    name = "mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        if snapshot.mid is None:
            return None
        return FairValueEstimate(price=float(snapshot.mid), method=self.name, confidence=0.7)


class MicropriceEstimator:
    name = "microprice"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        if snapshot.microprice is None:
            return None
        components: Mapping[str, Scalar] = MappingProxyType(
            {"imbalance": float(snapshot.book_imbalance or 0.0)}
        )
        return FairValueEstimate(
            price=float(snapshot.microprice),
            method=self.name,
            confidence=0.8,
            components=components,
        )


class RollingMidEstimator:
    name = "rolling_mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        history = list(memory.recent_mids)
        if snapshot.mid is not None:
            history.append(float(snapshot.mid))
        if not history:
            return None
        return FairValueEstimate(
            price=sum(history) / len(history),
            method=self.name,
            confidence=0.65,
        )


class WeightedMidEstimator:
    name = "weighted_mid"
    LOOKBACK = 4

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        history = memory.recent_mids[-self.LOOKBACK :]
        if snapshot.mid is None:
            # Fall back to pure history if the book is one-sided.
            if not history:
                return None
            weights = list(range(1, len(history) + 1))
            return FairValueEstimate(
                price=weighted_average(history, weights),
                method=self.name,
                confidence=0.55,
            )
        values = [*history, float(snapshot.mid)]
        weights = list(range(1, len(values) + 1))
        return FairValueEstimate(
            price=weighted_average(values, weights),
            method=self.name,
            confidence=0.7,
        )


class DepthMidEstimator:
    name = "depth_mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        del memory, config
        if not snapshot.bids or not snapshot.asks:
            return None

        bid_volume = sum(level.volume for level in snapshot.bids)
        ask_volume = sum(level.volume for level in snapshot.asks)
        if bid_volume <= 0 or ask_volume <= 0:
            return None

        bid_vwap = sum(level.price * level.volume for level in snapshot.bids) / bid_volume
        ask_vwap = sum(level.price * level.volume for level in snapshot.asks) / ask_volume

        return FairValueEstimate(
            price=(bid_vwap + ask_vwap) / 2.0,
            method=self.name,
            confidence=0.75,
            components=MappingProxyType(
                {
                    "bid_vwap": bid_vwap,
                    "ask_vwap": ask_vwap,
                }
            ),
        )


ESTIMATORS: Mapping[str, Estimator] = MappingProxyType(
    {
        "anchor": AnchorEstimator(),
        "mid": MidEstimator(),
        "microprice": MicropriceEstimator(),
        "rolling_mid": RollingMidEstimator(),
        "weighted_mid": WeightedMidEstimator(),
        "depth_mid": DepthMidEstimator(),
    }
)


class FairValueEngine:
    """Resolves fair-value estimates with a per-product fallback chain."""

    def __init__(self, estimators: Mapping[str, Estimator] | None = None) -> None:
        self._estimators: dict[str, Estimator] = dict(estimators or ESTIMATORS)

    def register(self, estimator: Estimator) -> None:
        self._estimators[estimator.name] = estimator

    def known_estimators(self) -> tuple[str, ...]:
        return tuple(sorted(self._estimators))

    def estimate(
        self,
        product: str,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate:
        """Resolve the primary + fallback chain; never returns ``None``.

        If every configured estimator declines, drop to an anchor-price
        fallback, and finally a zero-confidence zero-price marker so the
        caller can still proceed. The doctrine Invariant 5: a fallback
        path always exists.
        """
        del product  # reserved for future per-product registries
        chain: list[str] = [config.fair_value_method, *config.fair_value_fallbacks]
        for name in chain:
            estimator = self._estimators.get(name)
            if estimator is None:
                continue
            result = estimator.estimate(snapshot, memory, config)
            if result is not None:
                return result
        if config.anchor_price is not None:
            return FairValueEstimate(
                price=float(config.anchor_price),
                method="anchor_fallback",
                confidence=0.1,
            )
        return FairValueEstimate(price=0.0, method="zero_fallback", confidence=0.0)

    def estimate_all(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> dict[str, FairValueEstimate]:
        """Run every registered estimator on the same snapshot.

        Skips estimators that return ``None``. Useful for Phase 3
        side-by-side fair-value inference experiments.
        """
        results: dict[str, FairValueEstimate] = {}
        for name, estimator in self._estimators.items():
            result = estimator.estimate(snapshot, memory, config)
            if result is not None:
                results[name] = result
        return results

# ========================================================================
# src/core/state_store.py
# ========================================================================

"""Versioned persistence for the trader's rolling ``EngineState``.

Prosperity calls ``Trader.run()`` in an effectively stateless container.
Anything we want to remember across iterations must live in ``traderData``,
which is a string with a hard 50,000 character budget.

This module is the single authoritative boundary between ``EngineState``
(the in-memory dataclass the engine works with) and the opaque string we
hand back to the platform.

Guarantees:
- ``load()`` never raises on empty, ``None``, or malformed input. It falls
  back to a fresh ``EngineState`` with the current version.
- ``save()`` always returns a string whose length is ``<= max_chars``.
- Schema migration hook ``_migrate`` is called when the stored version is
  older than the current version. Today it is a no-op, but the plumbing is
  in place so strategy history survives a version bump.
- Persisted history lists are clamped at load time so an adversarial or
  accidentally-bloated ``traderData`` cannot grow unbounded after a restart.
"""




_MAX_PERSISTED_HISTORY = 64
_TRUNCATED_HISTORY_KEEP = 8


class StateStore:
    def __init__(
        self,
        version: int = 1,
        max_chars: int = 50_000,
        max_history: int = _MAX_PERSISTED_HISTORY,
        truncated_history_keep: int = _TRUNCATED_HISTORY_KEEP,
    ) -> None:
        if version < 1:
            raise ValueError("version must be >= 1")
        if max_chars <= 0:
            raise ValueError("max_chars must be > 0")
        if max_history < 0 or truncated_history_keep < 0:
            raise ValueError("history bounds must be >= 0")
        if truncated_history_keep > max_history:
            raise ValueError("truncated_history_keep must be <= max_history")

        self.version = version
        self.max_chars = max_chars
        self.max_history = max_history
        self.truncated_history_keep = truncated_history_keep

    # ------------------------------------------------------------------ load

    def load(self, trader_data: str | None) -> EngineState:
        """Parse ``traderData`` into an ``EngineState``.

        Returns a fresh state on any failure mode. This is intentional:
        a corrupted state blob must never crash ``Trader.run()``.
        """
        if not trader_data:
            return EngineState(version=self.version)

        try:
            raw = json.loads(trader_data)
        except (TypeError, ValueError):
            return EngineState(version=self.version)

        if not isinstance(raw, dict):
            return EngineState(version=self.version)

        stored_version = self._safe_int(raw.get("version"), default=self.version)
        if stored_version != self.version:
            raw = self._migrate(raw, from_version=stored_version)

        state = EngineState(version=self.version)
        raw_products = raw.get("products", {})
        if not isinstance(raw_products, dict):
            return state

        for product, payload in raw_products.items():
            if not isinstance(product, str) or not isinstance(payload, dict):
                continue
            state.products[product] = ProductMemory(
                recent_mids=self._coerce_float_list(payload.get("recent_mids")),
                recent_spreads=self._coerce_float_list(payload.get("recent_spreads")),
                counters=self._coerce_int_dict(payload.get("counters")),
                flags=self._coerce_bool_dict(payload.get("flags")),
                values=self._coerce_float_dict(payload.get("values")),
            )

        return state

    # ------------------------------------------------------------------ save

    def save(self, state: EngineState) -> str:
        """Serialize ``state`` to a platform-safe string.

        Strategy:
        1. Full encode with current contents.
        2. If too big, encode a truncated version with the most recent
           ``truncated_history_keep`` mids/spreads only.
        3. If still too big, drop all product memory and return an
           empty-products marker.

        ``_encode`` uses ``allow_nan=False`` so NaN/Infinity leaking
        into ``ProductMemory.values`` cannot produce spec-violating
        JSON that Prosperity's parser would silently reject. If it
        raises, we drop all memory rather than returning a bad blob.
        """
        try:
            payload = asdict(state)
            payload["version"] = self.version

            encoded = self._encode(payload)
            if len(encoded) <= self.max_chars:
                return encoded

            compact: dict[str, Any] = {"version": self.version, "products": {}}
            for product, memory in state.products.items():
                compact["products"][product] = {
                    "recent_mids": memory.recent_mids[-self.truncated_history_keep :],
                    "recent_spreads": memory.recent_spreads[-self.truncated_history_keep :],
                    "counters": memory.counters,
                    "flags": memory.flags,
                    "values": memory.values,
                }
            encoded = self._encode(compact)
            if len(encoded) <= self.max_chars:
                return encoded
        except ValueError:
            warnings.warn(
                "StateStore.save refused to emit non-finite values "
                "(NaN/Infinity) and dropped all product memory for this "
                "iteration. Investigate which strategy wrote the bad value.",
                RuntimeWarning,
                stacklevel=2,
            )

        return self._encode({"version": self.version, "products": {}})

    # -------------------------------------------------------------- migrate

    def _migrate(self, raw: dict[str, Any], *, from_version: int) -> dict[str, Any]:
        """Hook for future schema migrations.

        The base implementation is a no-op and warns loudly when called
        with a mismatched ``from_version``. Subclasses should override
        this to dispatch on ``from_version`` and silently perform
        whatever rewrites the new schema needs.
        """
        if from_version != self.version:
            warnings.warn(
                f"StateStore._migrate invoked with from_version={from_version} "
                f"(current={self.version}) but the base implementation is a no-op. "
                "Override _migrate or bump the schema carefully.",
                UserWarning,
                stacklevel=2,
            )
        return raw

    # ---------------------------------------------------------------- utils

    @staticmethod
    def _encode(payload: dict[str, Any]) -> str:
        return json.dumps(payload, separators=(",", ":"), sort_keys=True, allow_nan=False)

    @staticmethod
    def _safe_int(value: Any, default: int) -> int:
        try:
            return int(value)
        except (TypeError, ValueError):
            return default

    def _coerce_float_list(self, value: Any) -> list[float]:
        if not isinstance(value, list):
            return []
        coerced = [
            float(item)
            for item in value
            if isinstance(item, (int, float)) and not isinstance(item, bool)
        ]
        if len(coerced) > self.max_history:
            coerced = coerced[-self.max_history :]
        return coerced

    @staticmethod
    def _coerce_int_dict(value: Any) -> dict[str, int]:
        if not isinstance(value, dict):
            return {}
        out: dict[str, int] = {}
        for key, item in value.items():
            if isinstance(item, bool):
                continue
            if isinstance(item, (int, float)):
                out[str(key)] = int(item)
        return out

    @staticmethod
    def _coerce_bool_dict(value: Any) -> dict[str, bool]:
        if not isinstance(value, dict):
            return {}
        out: dict[str, bool] = {}
        for key, item in value.items():
            if isinstance(item, bool):
                out[str(key)] = item
        return out

    @staticmethod
    def _coerce_float_dict(value: Any) -> dict[str, float]:
        if not isinstance(value, dict):
            return {}
        out: dict[str, float] = {}
        for key, item in value.items():
            if isinstance(item, bool):
                continue
            if isinstance(item, (int, float)):
                out[str(key)] = float(item)
        return out

# ========================================================================
# src/core/signals.py
# ========================================================================

"""Translate fair value + snapshot + config into a trading intent.

This module converts "what do we believe" (the fair value estimate)
into "what would we want to do about it" (a ``SignalIntent`` naming
taker thresholds, maker prices, and the execution mode). It deliberately
does NOT emit ``Order``s — that's the execution engine's job.

Capacity recovery rule:
- When ``|position / limit| >= flatten_threshold`` the engine enters
  "recovery" mode. It stops adding to the side that already has
  exposure and tightens the opposite side toward fair value.
- In practice that means a long position disables buy intent entirely
  (maker bid size = 0 AND taker ``buy_below`` is set to ``None``) and
  pulls the maker ask in to fair value so inventory unwinds fastest.
"""





class SignalEngine:
    def build_market_making_intent(
        self,
        product: str,
        snapshot: NormalizedSnapshot,
        fair_value: FairValueEstimate,
        config: ProductConfig,
    ) -> SignalIntent:
        position_ratio = snapshot.position / config.position_limit if config.position_limit else 0.0
        skew = position_ratio * config.inventory_skew
        flattening = abs(position_ratio) >= config.flatten_threshold

        buy_below: float | None = fair_value.price - config.taker_edge - skew
        sell_above: float | None = fair_value.price + config.taker_edge - skew

        raw_bid = math.floor(fair_value.price - config.maker_edge - skew)
        raw_ask = math.ceil(fair_value.price + config.maker_edge - skew)

        if snapshot.best_ask is not None:
            raw_bid = min(raw_bid, snapshot.best_ask.price - config.tick_size)
        if snapshot.best_bid is not None:
            raw_ask = max(raw_ask, snapshot.best_bid.price + config.tick_size)

        bid_size = config.quote_size
        ask_size = config.quote_size
        mode: ExecutionMode = "hybrid"
        rationale = "market_make_around_fair_value"

        if flattening:
            mode = "recovery"
            rationale = "inventory_recovery"
            if snapshot.position > 0:
                # Long: stop buying entirely, pull ask toward fair value.
                bid_size = 0
                buy_below = None
                raw_ask = min(raw_ask, math.floor(fair_value.price))
            elif snapshot.position < 0:
                # Short: stop selling entirely, pull bid toward fair value.
                ask_size = 0
                sell_above = None
                raw_bid = max(raw_bid, math.ceil(fair_value.price))

        quote = QuoteIntent(
            bid_price=raw_bid if bid_size > 0 else None,
            bid_size=bid_size,
            ask_price=raw_ask if ask_size > 0 else None,
            ask_size=ask_size,
        )

        return SignalIntent(
            product=product,
            fair_value=fair_value,
            mode=mode,
            buy_below=buy_below,
            sell_above=sell_above,
            quote=quote,
            rationale=rationale,
            metadata={
                "position_ratio": round(position_ratio, 4),
                "skew": round(skew, 4),
                "flattening": flattening,
            },
        )

# ========================================================================
# src/core/execution.py
# ========================================================================

class ExecutionEngine:
    def generate_orders(
        self,
        snapshot: NormalizedSnapshot,
        intent: SignalIntent,
        config: ProductConfig,
    ) -> list[Order]:
        orders: list[Order] = []

        remaining_buy = config.max_aggressive_size
        remaining_sell = config.max_aggressive_size

        if intent.buy_below is not None:
            for ask in snapshot.asks:
                if ask.price > intent.buy_below or remaining_buy <= 0:
                    break
                quantity = min(ask.volume, remaining_buy)
                if quantity > 0:
                    orders.append(Order(snapshot.product, ask.price, quantity))
                    remaining_buy -= quantity

        if intent.sell_above is not None:
            for bid in snapshot.bids:
                if bid.price < intent.sell_above or remaining_sell <= 0:
                    break
                quantity = min(bid.volume, remaining_sell)
                if quantity > 0:
                    orders.append(Order(snapshot.product, bid.price, -quantity))
                    remaining_sell -= quantity

        if intent.quote is not None:
            if intent.quote.bid_price is not None and intent.quote.bid_size > 0:
                orders.append(
                    Order(snapshot.product, intent.quote.bid_price, intent.quote.bid_size)
                )
            if intent.quote.ask_price is not None and intent.quote.ask_size > 0:
                orders.append(
                    Order(snapshot.product, intent.quote.ask_price, -intent.quote.ask_size)
                )

        return orders

# ========================================================================
# src/core/risk.py
# ========================================================================

"""Per-product position legality and clipping.

This is the single place where we enforce Prosperity's hard position
limits. Strategies must never assume their orders are final: the risk
manager always owns the decision about what quantity actually leaves the
trader.

The clipping model:
- We compute remaining buy and sell capacity from the current position
  and the product's limit.
- We walk through the strategy's orders in submission order, reducing
  each to fit the remaining capacity on that side.
- Orders that would have zero quantity after clipping are dropped.
- Zero-quantity input orders are silently dropped.
- An order whose ``symbol`` does not match the product being clipped is
  a programming error and raises ``ValueError`` immediately.

The rationale for clipping per-side instead of per-order is that
Prosperity will reject an entire side if the aggregate would breach the
limit. By aggregating capacity here, we make the exchange reject nothing.
"""





@dataclass(frozen=True)
class Capacity:
    buy: int
    sell: int


class RiskManager:
    @staticmethod
    def remaining_buy_capacity(position: int, limit: int) -> int:
        if limit < 0:
            raise ValueError("limit must be >= 0")
        return max(0, limit - position)

    @staticmethod
    def remaining_sell_capacity(position: int, limit: int) -> int:
        if limit < 0:
            raise ValueError("limit must be >= 0")
        return max(0, limit + position)

    @classmethod
    def capacity(cls, position: int, limit: int) -> Capacity:
        return Capacity(
            buy=cls.remaining_buy_capacity(position, limit),
            sell=cls.remaining_sell_capacity(position, limit),
        )

    @staticmethod
    def inventory_ratio(position: int, limit: int) -> float:
        if limit <= 0:
            return 0.0
        return position / limit

    def clip_orders(
        self,
        product: str,
        orders: list[Order],
        current_position: int,
        limit: int,
    ) -> list[Order]:
        if limit < 0:
            raise ValueError("limit must be >= 0")

        buy_capacity = self.remaining_buy_capacity(current_position, limit)
        sell_capacity = self.remaining_sell_capacity(current_position, limit)
        clipped: list[Order] = []

        for order in orders:
            if order.symbol != product:
                raise ValueError(
                    f"risk.clip_orders: order symbol {order.symbol!r} does not "
                    f"match product {product!r}"
                )
            if order.quantity == 0:
                continue

            if order.quantity > 0:
                quantity = min(order.quantity, buy_capacity)
                if quantity > 0:
                    clipped.append(Order(order.symbol, order.price, quantity))
                    buy_capacity -= quantity
            else:
                quantity = min(-order.quantity, sell_capacity)
                if quantity > 0:
                    clipped.append(Order(order.symbol, order.price, -quantity))
                    sell_capacity -= quantity

        return clipped

# ========================================================================
# src/strategies/base.py
# ========================================================================

@dataclass(frozen=True)
class StrategyContext:
    product: str
    snapshot: NormalizedSnapshot
    memory: ProductMemory
    config: ProductConfig


class BaseStrategy(ABC):
    @abstractmethod
    def generate_intent(self, context: StrategyContext) -> SignalIntent:
        raise NotImplementedError

# ========================================================================
# src/strategies/market_making.py
# ========================================================================

"""Single market-making strategy shared across products.

This is the only strategy in the engine today. It combines:

1. a fair-value estimate from ``FairValueEngine`` (which may be an
   anchor, mid, microprice, rolling or weighted mid depending on the
   product's config), and
2. a market-making intent from ``SignalEngine`` built around that
   fair value.

Different products tune *how* this strategy behaves via
``ProductConfig`` (edge widths, quote sizes, flatten thresholds) and
*which* fair-value estimator runs (``fair_value_method`` +
``fair_value_fallbacks``). A second strategy module only exists once
there is a genuinely different decision rule that cannot be reduced to
config.
"""




class MarketMakingStrategy(BaseStrategy):
    def __init__(self, fair_value_engine: FairValueEngine, signal_engine: SignalEngine) -> None:
        self.fair_value_engine = fair_value_engine
        self.signal_engine = signal_engine

    def generate_intent(self, context: StrategyContext) -> SignalIntent:
        fair_value = self.fair_value_engine.estimate(
            context.product, context.snapshot, context.memory, context.config
        )
        return self.signal_engine.build_market_making_intent(
            context.product, context.snapshot, fair_value, context.config
        )

# ========================================================================
# src/strategies/__init__.py
# ========================================================================

"""Strategy registry.

Product configs reference a strategy by name (``ProductConfig.strategy_name``)
and the ``Trader`` looks up that name in ``STRATEGY_REGISTRY`` to
construct the strategy instance.

Adding a new strategy means:

1. implement a subclass of ``BaseStrategy`` in a new module,
2. register it here under a unique name,
3. set ``ProductConfig.strategy_name`` on the products that should use
   it.

No changes to ``Trader.__init__`` are needed for new products that
reuse an existing strategy.
"""




StrategyFactory = Callable[[FairValueEngine, SignalEngine], BaseStrategy]

STRATEGY_REGISTRY: Mapping[str, StrategyFactory] = MappingProxyType(
    {
        "market_making": MarketMakingStrategy,
    }
)

__all__ = [
    "STRATEGY_REGISTRY",
    "BaseStrategy",
    "MarketMakingStrategy",
    "StrategyFactory",
]

# ========================================================================
# src/trader.py
# ========================================================================

"""Entrypoint for the Prosperity live trading container.

Responsibilities of this file are deliberately narrow:

1. Restore persistent state from ``state.traderData``.
2. Normalize the incoming ``TradingState`` into canonical snapshots.
3. Dispatch each known product to its configured strategy via the
   ``STRATEGY_REGISTRY`` in ``src/strategies/``.
4. Route the strategy's intent through execution and risk layers.
5. Update rolling per-product memory.
6. Serialize next-iteration state back into ``traderData``.
7. Return ``(orders, conversions, traderData)``.

This file never contains product-specific pricing or execution
heuristics. Those live in ``strategies/`` and ``core/``.

Safety: ``run()`` is wrapped in a top-level safety net. If any
downstream module raises, the trader returns an empty orders dict and
preserves the previous ``traderData`` so the Prosperity container does
not crash. Tests can set ``_reraise_exceptions=True`` to opt out and
surface errors.
"""




_LOG = logging.getLogger(__name__)


class Trader:
    def __init__(
        self,
        config: EngineConfig | None = None,
        *,
        reraise_exceptions: bool = False,
    ) -> None:
        self.config = config or default_engine_config()
        self.state_store = StateStore(
            version=self.config.state_version,
            max_chars=self.config.max_trader_data_chars,
        )
        self.market_data = MarketDataAdapter()
        self.fair_value_engine = FairValueEngine()
        self.signal_engine = SignalEngine()
        self.execution_engine = ExecutionEngine()
        self.risk_manager = RiskManager()
        self.logger = DecisionLogger()
        self._reraise_exceptions = reraise_exceptions
        self.strategies: dict[str, BaseStrategy] = self._build_strategies()

    # ---------------------------------------------------------- setup

    def _build_strategies(self) -> dict[str, BaseStrategy]:
        strategies: dict[str, BaseStrategy] = {}
        for product_config in self.config.products.values():
            name = product_config.strategy_name
            if name in strategies:
                continue
            factory = STRATEGY_REGISTRY.get(name)
            if factory is None:
                _LOG.warning("Unknown strategy %r for product config; will be skipped", name)
                continue
            strategies[name] = factory(self.fair_value_engine, self.signal_engine)
        return strategies

    # ---------------------------------------------------------- contract

    # Some Prosperity rounds require a ``bid()`` method on Trader.
    # Keep this stub so contract changes do not break submissions.
    def bid(self) -> int:
        return 15

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        """Entry point called by the Prosperity container.

        Wraps ``_run_body`` in a top-level safety net. An unhandled
        exception in any sub-module would otherwise crash the container
        and lose the iteration entirely.
        """
        try:
            return self._run_body(state)
        except Exception:
            _LOG.exception("Trader.run crashed; returning empty orders")
            if self._reraise_exceptions:
                raise
            return {}, 0, state.traderData

    # ---------------------------------------------------------- body

    def _run_body(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        engine_state = self.state_store.load(state.traderData)
        engine_state.version = self.config.state_version

        snapshots = self.market_data.normalize_state(state)
        results: dict[str, list[Order]] = {}

        for product, snapshot in snapshots.items():
            product_config = self.config.product_config(product)
            if product_config is None:
                results[product] = []
                continue

            strategy = self.strategies.get(product_config.strategy_name)
            if strategy is None:
                results[product] = []
                continue

            memory = engine_state.for_product(product)
            legal_orders = self._step_product(
                product=product,
                snapshot=snapshot,
                memory=memory,
                product_config=product_config,
                strategy=strategy,
                timestamp=state.timestamp,
            )
            results[product] = legal_orders
            self._update_memory(memory, snapshot, product_config.history_length)

        trader_data = self.state_store.save(engine_state)
        conversions = 0
        return results, conversions, trader_data

    # ---------------------------------------------------------- per-product

    def _step_product(
        self,
        *,
        product: str,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        product_config: ProductConfig,
        strategy: BaseStrategy,
        timestamp: int,
    ) -> list[Order]:
        context = StrategyContext(
            product=product,
            snapshot=snapshot,
            memory=memory,
            config=product_config,
        )
        intent = strategy.generate_intent(context)
        raw_orders = self.execution_engine.generate_orders(snapshot, intent, product_config)
        legal_orders = self.risk_manager.clip_orders(
            product=product,
            orders=raw_orders,
            current_position=snapshot.position,
            limit=product_config.position_limit,
        )

        self.logger.record(
            {
                "timestamp": timestamp,
                "product": product,
                "fair_value": round(intent.fair_value.price, 4),
                "method": intent.fair_value.method,
                "position": snapshot.position,
                "mode": intent.mode,
                "orders": [(order.price, order.quantity) for order in legal_orders],
            }
        )
        return legal_orders

    @staticmethod
    def _update_memory(
        memory: ProductMemory, snapshot: NormalizedSnapshot, history_length: int
    ) -> None:
        if history_length <= 0:
            return
        if snapshot.mid is not None:
            bounded_append(memory.recent_mids, float(snapshot.mid), history_length)
        if snapshot.spread is not None:
            bounded_append(memory.recent_spreads, float(snapshot.spread), history_length)

    # ---------------------------------------------------------- helpers

    def reset(self) -> None:
        """Drop any transient in-memory state (diagnostics only)."""
        self.logger = DecisionLogger()

    def engine_state_from(self, trader_data: str | None) -> EngineState:
        """Expose the state store to callers that need to inspect memory."""
        return self.state_store.load(trader_data)
