# Auto-generated by src/scripts/export_submission.py. DO NOT EDIT.
# Datamodel mode: platform.
# Source modules: 18.

# ========================================================================
# ROUND-1 UPLOAD VARIANT: test
# Label   : Round-1 ad-hoc directional (wall ASH + buy-and-hold PEPPER)
# Purpose : Directional experiment. Wall-based ASH (same leg as F5 / H1) + buy-and-hold PEPPER — take any ask up to the position limit, then hold. Upper-bound reference for how much of PEPPER's official PnL is drift MTM vs market-making edge. Additive; never replaces any shipped bundle.
# Factory : src.core.config.round1_test_engine_config
# Built   : 2026-04-15T17:10:20.154199+00:00 (commit 7bc6241)
# Embedded product configs:
#   ASH_COATED_OSMIUM: {'position_limit': 80, 'fair_value_method': 'wall_mid', 'fair_value_fallbacks': ('mid', 'microprice'), 'anchor_price': 10000.0, 'taker_edge': 0.5, 'maker_edge': 1.5, 'quote_size': 5, 'max_aggressive_size': 10, 'inventory_skew': 4.0, 'flatten_threshold': 0.7, 'history_length': 48, 'taker_edge_buy': None, 'taker_edge_sell': None, 'early_window': 0, 'early_taker_edge_buy': None, 'early_taker_edge_sell': None, 'early_short_cap': None, 'early_short_skew_mult': 1.0, 'early_short_flatten': None}
#   INTARIAN_PEPPER_ROOT: {'position_limit': 80, 'fair_value_method': 'mid', 'fair_value_fallbacks': (), 'anchor_price': None, 'taker_edge': 1.0, 'maker_edge': 1.5, 'quote_size': 4, 'max_aggressive_size': 80, 'inventory_skew': 2.0, 'flatten_threshold': 0.8, 'history_length': 48, 'taker_edge_buy': None, 'taker_edge_sell': None, 'early_window': 0, 'early_taker_edge_buy': None, 'early_taker_edge_sell': None, 'early_short_cap': None, 'early_short_skew_mult': 1.0, 'early_short_flatten': None}
# ========================================================================

from __future__ import annotations

from datamodel import Order, OrderDepth, Trade, TradingState

from collections.abc import Sequence
from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Literal
import json
from typing import Protocol
import warnings
from dataclasses import asdict
from typing import Any
from collections import Counter
import math
from dataclasses import dataclass
from abc import ABC, abstractmethod
from collections.abc import Callable, Mapping
import logging

# ========================================================================
# src/core/utils.py
# ========================================================================

def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(value, high))


def bounded_append(values: list[float], value: float, maxlen: int) -> None:
    values.append(value)
    if len(values) > maxlen:
        del values[: len(values) - maxlen]


def weighted_average(values: Sequence[float], weights: Sequence[float]) -> float:
    if len(values) != len(weights):
        raise ValueError("values and weights must have the same length")
    total_weight = float(sum(weights))
    if total_weight == 0:
        raise ValueError("weights must not sum to zero")
    return sum(value * weight for value, weight in zip(values, weights, strict=True)) / total_weight

# ========================================================================
# src/core/types.py
# ========================================================================

"""Shared engine types.

These types are the stable vocabulary spoken by every engine layer:
fair value, signals, execution, risk, and strategies.

Design notes:
- ``NormalizedSnapshot`` is frozen. Downstream code should not mutate it.
- ``ProductMemory`` is mutable because it is the authoritative rolling state
  we persist through ``traderData``; mutation is explicit and local.
- ``FairValueEstimate`` and ``SignalIntent`` are frozen so strategy code
  cannot accidentally mutate outputs of the fair value or signal stages.
  Their container fields (``components``, ``metadata``) are typed as
  ``Mapping`` and default to ``MappingProxyType({})`` so mutation is
  rejected at runtime as well as discouraged by the type system.
"""



Product = str
Timestamp = int
Scalar = int | float | str | bool
ExecutionMode = Literal["idle", "maker", "taker", "recovery", "hybrid"]


def _empty_scalar_map() -> Mapping[str, Scalar]:
    return MappingProxyType({})


@dataclass(frozen=True)
class BookLevel:
    price: int
    volume: int


@dataclass(frozen=True)
class TradePrint:
    price: int
    quantity: int
    buyer: str | None = None
    seller: str | None = None
    timestamp: int = 0
    source: Literal["own", "market"] = "market"


@dataclass(frozen=True)
class NormalizedSnapshot:
    product: Product
    timestamp: Timestamp
    bids: tuple[BookLevel, ...] = ()
    asks: tuple[BookLevel, ...] = ()
    position: int = 0
    trades: tuple[TradePrint, ...] = ()

    @property
    def best_bid(self) -> BookLevel | None:
        return self.bids[0] if self.bids else None

    @property
    def best_ask(self) -> BookLevel | None:
        return self.asks[0] if self.asks else None

    @property
    def mid(self) -> float | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return (self.best_bid.price + self.best_ask.price) / 2.0

    @property
    def spread(self) -> float | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return float(self.best_ask.price - self.best_bid.price)

    @property
    def book_imbalance(self) -> float | None:
        """Top-of-book imbalance in [-1, 1], positive = bid-heavy."""
        if self.best_bid is None or self.best_ask is None:
            return None
        total = self.best_bid.volume + self.best_ask.volume
        if total <= 0:
            return None
        return (self.best_bid.volume - self.best_ask.volume) / total

    @property
    def microprice(self) -> float | None:
        """Volume-weighted best price, i.e. mid tilted toward the thicker side."""
        if self.best_bid is None or self.best_ask is None:
            return None
        total = self.best_bid.volume + self.best_ask.volume
        if total <= 0:
            return None
        return (
            (self.best_bid.price * self.best_ask.volume)
            + (self.best_ask.price * self.best_bid.volume)
        ) / total

    def total_bid_volume(self, depth: int | None = None) -> int:
        levels = self.bids if depth is None else self.bids[:depth]
        return sum(level.volume for level in levels)

    def total_ask_volume(self, depth: int | None = None) -> int:
        levels = self.asks if depth is None else self.asks[:depth]
        return sum(level.volume for level in levels)

    def top_bids(self, depth: int) -> tuple[BookLevel, ...]:
        if depth <= 0:
            return ()
        return self.bids[:depth]

    def top_asks(self, depth: int) -> tuple[BookLevel, ...]:
        if depth <= 0:
            return ()
        return self.asks[:depth]


@dataclass
class ProductMemory:
    recent_mids: list[float] = field(default_factory=list)
    recent_spreads: list[float] = field(default_factory=list)
    counters: dict[str, int] = field(default_factory=dict)
    flags: dict[str, bool] = field(default_factory=dict)
    values: dict[str, float] = field(default_factory=dict)


@dataclass
class EngineState:
    version: int = 1
    products: dict[Product, ProductMemory] = field(default_factory=dict)

    def for_product(self, product: Product) -> ProductMemory:
        memory = self.products.get(product)
        if memory is None:
            memory = ProductMemory()
            self.products[product] = memory
        return memory


@dataclass(frozen=True)
class FairValueEstimate:
    price: float
    method: str
    confidence: float | None = None
    components: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)


@dataclass(frozen=True)
class QuoteIntent:
    bid_price: int | None = None
    bid_size: int = 0
    ask_price: int | None = None
    ask_size: int = 0


@dataclass(frozen=True)
class SignalIntent:
    product: Product
    fair_value: FairValueEstimate
    mode: ExecutionMode = "idle"
    buy_below: float | None = None
    sell_above: float | None = None
    quote: QuoteIntent | None = None
    rationale: str = ""
    metadata: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)


# ---------------------------------------------------------------- scanner


@dataclass(frozen=True)
class ScannerConfig:
    """Controls whether and how verbosely the flow scanner runs.

    Verbosity levels:
    - 0 (default): silent — scanner runs and persists state but adds
      nothing to the decision logger. Suitable for live submission.
    - 1: flags-only — appends ``scan_flags`` to the logger event.
    - 2: full report — appends the complete ``FlowReport`` dict to the
      logger event. Intended for offline review scripts only.
    """

    enabled: bool = True
    extrema_window: int = 20
    extrema_tolerance: float = 1.0
    flow_decay: float = 0.8
    repeated_size_threshold: int = 3
    verbosity: int = 0


@dataclass(frozen=True)
class ResidualConfig:
    """Controls the optional residual capacity utilizer.

    Ships disabled (framework-only). Enable only after the enablement
    gate is passed: compare baseline vs baseline+residual on PnL, trade
    count, maker/taker mix, markouts, and time-near-limits. Record
    results in a review note before flipping the flag.
    """

    enabled: bool = False
    residual_edge: float = 2.0
    residual_size: int = 2


@dataclass(frozen=True)
class FlowReport:
    """Observational summary of trade-flow patterns for a single step.

    All fields are ephemeral — only ``flow_score`` (via
    ``ProductMemory.values``) and ``step_count`` (via
    ``ProductMemory.counters``) are persisted across calls.

    ``net_flow`` is a heuristic proxy for directional pressure, not
    true aggressor-side inference. The sign convention is: buyer-only
    trade -> +qty, seller-only -> -qty, both or neither -> 0.
    """

    product: Product
    timestamp: Timestamp
    repeated_sizes: Mapping[int, int]
    net_flow: int
    flow_score: float
    near_high: bool
    near_low: bool
    flags: tuple[str, ...]
    metadata: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)

# ========================================================================
# src/core/config.py
# ========================================================================

"""Engine and per-product configuration.

``ProductConfig`` is a frozen dataclass that binds every tunable knob for
one product. ``EngineConfig`` bundles a set of product configs with
runtime-wide knobs such as the state store version and the trader data
char budget.

Fair value resolution:

- ``fair_value_method`` names the primary estimator.
- ``fair_value_fallbacks`` is an ordered tuple of estimator names that
  will be tried in turn if the primary returns ``None`` (missing data,
  insufficient history, etc.). The doctrine requires a fallback path to
  always exist; this is where it lives.

Validation happens at construction time so misconfigured runs fail
immediately instead of producing subtle bad behavior deep inside the
live loop.
"""




KNOWN_STRATEGY_NAMES: tuple[str, ...] = ("buy_and_hold", "market_making")
KNOWN_ESTIMATOR_NAMES: tuple[str, ...] = (
    "anchor",
    "depth_mid",
    "ewma_mid",
    "filtered_wall_mid",
    "hybrid_wall_micro",
    "linear_drift",
    "microprice",
    "mid",
    "rolling_mid",
    "wall_mid",
    "weighted_mid",
)


def _format_known_names(names: tuple[str, ...]) -> str:
    return ", ".join(names) if names else "<none>"


@dataclass(frozen=True)
class ProductConfig:
    position_limit: int
    strategy_name: str
    fair_value_method: str
    fair_value_fallbacks: tuple[str, ...] = ()
    tick_size: int = 1
    anchor_price: float | None = None
    taker_edge: float = 1.0
    maker_edge: float = 1.0
    quote_size: int = 5
    max_aggressive_size: int = 10
    inventory_skew: float = 2.0
    flatten_threshold: float = 0.8
    history_length: int = 32
    ewma_alpha: float | None = None
    # Phase-9 fastsearch knobs (all optional, neutral defaults).
    # See ``outputs/round_1/fastsearch/pepper_memo.md``.
    taker_edge_buy: float | None = None
    taker_edge_sell: float | None = None
    early_window: int = 0
    early_taker_edge_buy: float | None = None
    early_taker_edge_sell: float | None = None
    early_short_cap: int | None = None
    early_short_skew_mult: float = 1.0
    early_short_flatten: float | None = None

    def __post_init__(self) -> None:
        if self.strategy_name not in KNOWN_STRATEGY_NAMES:
            raise ValueError(
                "ProductConfig.strategy_name must be one of "
                f"{_format_known_names(KNOWN_STRATEGY_NAMES)} "
                f"(got {self.strategy_name!r})"
            )

        if self.fair_value_method not in KNOWN_ESTIMATOR_NAMES:
            raise ValueError(
                "ProductConfig.fair_value_method must be one of "
                f"{_format_known_names(KNOWN_ESTIMATOR_NAMES)} "
                f"(got {self.fair_value_method!r})"
            )

        unknown_fallbacks = tuple(
            name for name in self.fair_value_fallbacks if name not in KNOWN_ESTIMATOR_NAMES
        )
        if unknown_fallbacks:
            raise ValueError(
                "ProductConfig.fair_value_fallbacks contains unknown estimator(s) "
                f"{unknown_fallbacks}; known estimators: "
                f"{_format_known_names(KNOWN_ESTIMATOR_NAMES)}"
            )

        if self.position_limit <= 0:
            raise ValueError(
                f"ProductConfig.position_limit must be > 0 (got {self.position_limit})"
            )
        if self.tick_size <= 0:
            raise ValueError(f"ProductConfig.tick_size must be > 0 (got {self.tick_size})")
        if self.quote_size < 0:
            raise ValueError(f"ProductConfig.quote_size must be >= 0 (got {self.quote_size})")
        if self.max_aggressive_size < 0:
            raise ValueError(
                f"ProductConfig.max_aggressive_size must be >= 0 "
                f"(got {self.max_aggressive_size})"
            )
        if self.taker_edge < 0 or self.maker_edge < 0:
            raise ValueError("ProductConfig.*_edge must be >= 0")
        if self.inventory_skew < 0:
            raise ValueError("ProductConfig.inventory_skew must be >= 0")
        if not 0.0 <= self.flatten_threshold <= 1.0:
            raise ValueError(
                f"ProductConfig.flatten_threshold must be in [0, 1] "
                f"(got {self.flatten_threshold})"
            )
        if self.history_length < 0:
            raise ValueError("ProductConfig.history_length must be >= 0")
        if self.ewma_alpha is not None and not 0.0 < self.ewma_alpha <= 1.0:
            raise ValueError(f"ProductConfig.ewma_alpha must be in (0, 1] (got {self.ewma_alpha})")
        if self.fair_value_method == "anchor" and self.anchor_price is None:
            raise ValueError("ProductConfig: fair_value_method='anchor' requires anchor_price")
        if "anchor" in self.fair_value_fallbacks and self.anchor_price is None:
            raise ValueError(
                "ProductConfig: fair_value_fallbacks includes 'anchor' "
                "but anchor_price is not set"
            )
        # --- Phase-9 fastsearch knob validation ---
        if self.taker_edge_buy is not None and self.taker_edge_buy < 0:
            raise ValueError("ProductConfig.taker_edge_buy must be >= 0 when set")
        if self.taker_edge_sell is not None and self.taker_edge_sell < 0:
            raise ValueError("ProductConfig.taker_edge_sell must be >= 0 when set")
        if self.early_window < 0:
            raise ValueError("ProductConfig.early_window must be >= 0")
        if self.early_taker_edge_buy is not None and self.early_taker_edge_buy < 0:
            raise ValueError("ProductConfig.early_taker_edge_buy must be >= 0 when set")
        if self.early_taker_edge_sell is not None and self.early_taker_edge_sell < 0:
            raise ValueError("ProductConfig.early_taker_edge_sell must be >= 0 when set")
        if self.early_short_skew_mult < 0:
            raise ValueError("ProductConfig.early_short_skew_mult must be >= 0")
        if self.early_short_flatten is not None and not 0.0 <= self.early_short_flatten <= 1.0:
            raise ValueError(
                "ProductConfig.early_short_flatten must be in [0, 1] when set "
                f"(got {self.early_short_flatten})"
            )
        # An ``early_short_cap`` of e.g. -8 would allow a short of 8 before
        # the cap kicks in; 0 forbids ever going short. Very negative
        # caps are effectively a no-op. No hard numeric bound — just
        # flag values that are structurally nonsense.
        if self.early_short_cap is not None and self.early_short_cap > 0:
            raise ValueError(
                "ProductConfig.early_short_cap must be <= 0 when set "
                f"(got {self.early_short_cap}); use 0 to forbid ever going short"
            )


@dataclass(frozen=True)
class EngineConfig:
    state_version: int = 1
    max_trader_data_chars: int = 50_000
    diagnostics_verbosity: int = 1
    products: dict[str, ProductConfig] = field(default_factory=dict)
    scanner_config: ScannerConfig = field(default_factory=ScannerConfig)
    residual_config: ResidualConfig = field(default_factory=ResidualConfig)

    def __post_init__(self) -> None:
        if self.state_version < 1:
            raise ValueError("EngineConfig.state_version must be >= 1")
        if self.max_trader_data_chars <= 0:
            raise ValueError("EngineConfig.max_trader_data_chars must be > 0")

    def product_config(self, product: str) -> ProductConfig | None:
        return self.products.get(product)


def default_engine_config() -> EngineConfig:
    # Tutorial products (EMERALDS, TOMATOES) plus Round-1 products
    # (ASH_COATED_OSMIUM, INTARIAN_PEPPER_ROOT). All share the
    # market-making strategy and differ only by configuration. See
    # ``outputs/round_1/notes/strategy_family_proposal.md`` for the
    # per-product Round-1 family rationale.
    return EngineConfig(
        products={
            "EMERALDS": ProductConfig(
                position_limit=80,
                strategy_name="market_making",
                fair_value_method="anchor",
                fair_value_fallbacks=("microprice", "mid"),
                anchor_price=10_000.0,
                taker_edge=1.0,
                maker_edge=2.0,
                quote_size=5,
                max_aggressive_size=10,
                inventory_skew=8.0,
                flatten_threshold=0.75,
                history_length=32,
            ),
            "TOMATOES": ProductConfig(
                position_limit=80,
                strategy_name="market_making",
                fair_value_method="wall_mid",
                fair_value_fallbacks=("mid", "microprice"),
                taker_edge=1.0,
                maker_edge=1.0,
                quote_size=4,
                max_aggressive_size=8,
                inventory_skew=12.0,
                flatten_threshold=0.7,
                history_length=48,
            ),
            # --- Round 1 ---
            # ASH_COATED_OSMIUM: anchored oscillator at ~10 000 with a
            # 16-tick stable spread; classic wide-spread maker product.
            # Primary wall_mid tracks the center of mass of the visible
            # book and was the most cross-day robust in Phase 1
            # (outputs/round_1/research/ash_coated_osmium_dossier.md).
            # position_limit=80 — IMC-confirmed Round-1 per-product cap.
            "ASH_COATED_OSMIUM": ProductConfig(
                position_limit=80,
                strategy_name="market_making",
                fair_value_method="wall_mid",
                fair_value_fallbacks=("mid", "microprice"),
                anchor_price=10_000.0,  # fallback only (not primary)
                taker_edge=1.0,
                maker_edge=1.0,
                quote_size=5,
                max_aggressive_size=10,
                inventory_skew=4.0,
                flatten_threshold=0.7,
                history_length=48,
            ),
            # INTARIAN_PEPPER_ROOT: deterministic drift +0.1 per
            # timestamp step; the drift runs *continuously* across day
            # boundaries on the sample data, so the daily mean rises
            # ~1 000 per day (the Phase-2 "+1 000 overnight jump"
            # framing was a misread — see the dossier corrigendum
            # under outputs/round_1/research/intarian_pepper_root_dossier.md).
            # Fair value is tracked by the `linear_drift` estimator
            # (added in Phase 3) with a book-aware fallback chain for
            # warm-up and one-sided snapshots.
            #
            # Fallback-chain design note: this product has no
            # `anchor_price`, so the `FairValueEngine.estimate`
            # zero-fallback (price=0.0) is only avoided when at least
            # one entry in the chain always returns a value. The chain
            # below is ordered so that `linear_drift` (always returns
            # something after warm-up) and `mid` cover that role.
            # Candidates like `depth_mid` and `hybrid_wall_micro` cannot
            # be used as primaries here without adding such a safety
            # net — see outputs/round_1/notes/phase4_sweep_shortlist.md.
            # position_limit=80 — IMC-confirmed Round-1 per-product cap.
            "INTARIAN_PEPPER_ROOT": ProductConfig(
                position_limit=80,
                strategy_name="market_making",
                fair_value_method="linear_drift",
                fair_value_fallbacks=("depth_mid", "hybrid_wall_micro", "mid"),
                taker_edge=1.0,
                maker_edge=1.5,
                quote_size=4,
                max_aggressive_size=8,
                inventory_skew=2.0,
                flatten_threshold=0.8,
                history_length=48,
            ),
        }
    )


ROUND1_PRODUCTS: tuple[str, ...] = ("ASH_COATED_OSMIUM", "INTARIAN_PEPPER_ROOT")


def round1_engine_config() -> EngineConfig:
    """Engine config containing **only** the Round-1 products.

    Round-1 research scripts (sweeps, dossier, backtest runner) should
    use this so the tutorial products (EMERALDS, TOMATOES) do not
    silently join a round-1 replay. This keeps ``default_engine_config``
    intact for the tutorial harness while giving round-1 tooling a
    focused baseline to ``replace()`` from.
    """
    base = default_engine_config()
    products = {
        name: config
        for name in ROUND1_PRODUCTS
        if (config := base.product_config(name)) is not None
    }
    return EngineConfig(
        state_version=base.state_version,
        max_trader_data_chars=base.max_trader_data_chars,
        diagnostics_verbosity=base.diagnostics_verbosity,
        products=products,
        scanner_config=base.scanner_config,
        residual_config=base.residual_config,
    )


# Phase-6 upload variants. Each is a thin wrapper that overrides the
# per-product fair-value / edge / inventory parameters on top of the
# round-1 baseline. The three variants together are the Phase-6 upload
# shortlist (see ``docs/round_1/upload_plan.md``).


def _round1_engine_with(**per_product_overrides: dict[str, object]) -> EngineConfig:
    """Helper: apply per-product field overrides on top of round1_engine_config."""
    from dataclasses import replace

    base = round1_engine_config()
    products = dict(base.products)
    for product, overrides in per_product_overrides.items():
        current = base.product_config(product)
        if current is None:
            continue
        products[product] = replace(current, **overrides)
    return EngineConfig(
        state_version=base.state_version,
        max_trader_data_chars=base.max_trader_data_chars,
        diagnostics_verbosity=base.diagnostics_verbosity,
        products=products,
        scanner_config=base.scanner_config,
        residual_config=base.residual_config,
    )


def round1_baseline_engine_config() -> EngineConfig:
    """Phase-6 baseline / control — Phase-3 Round-1 defaults verbatim."""
    return round1_engine_config()


def round1_promoted_engine_config() -> EngineConfig:
    """Phase-6 promoted / robust default. See
    ``outputs/round_1/notes/phase5_review_shortlist.md``.
    """
    return _round1_engine_with(
        ASH_COATED_OSMIUM=dict(
            fair_value_method="ewma_mid",
            fair_value_fallbacks=("mid", "microprice"),
            maker_edge=1.0,
            taker_edge=0.25,
            inventory_skew=4.0,
            flatten_threshold=0.7,
            history_length=48,
        ),
        INTARIAN_PEPPER_ROOT=dict(
            fair_value_method="linear_drift",
            fair_value_fallbacks=("depth_mid", "hybrid_wall_micro", "mid"),
            maker_edge=1.0,
            taker_edge=2.0,
            inventory_skew=2.0,
            flatten_threshold=0.7,
            history_length=32,
        ),
    )


def round1_h1_engine_config() -> EngineConfig:
    """Phase-8.5 hybrid H1 — promoted PEPPER + alt wall_mid ASH.

    Additive; does not replace promoted / alt. See
    ``outputs/round_1/phase8_5/hybrid_memo.md``.
    """
    return _round1_engine_with(
        ASH_COATED_OSMIUM=dict(
            fair_value_method="wall_mid",
            fair_value_fallbacks=("mid", "microprice"),
            maker_edge=1.5,
            taker_edge=0.5,
            inventory_skew=4.0,
            flatten_threshold=0.7,
            history_length=48,
        ),
        INTARIAN_PEPPER_ROOT=dict(
            fair_value_method="linear_drift",
            fair_value_fallbacks=("depth_mid", "hybrid_wall_micro", "mid"),
            maker_edge=1.0,
            taker_edge=2.0,
            inventory_skew=2.0,
            flatten_threshold=0.7,
            history_length=32,
        ),
    )


def round1_f5_engine_config() -> EngineConfig:
    """Phase-9 fastsearch F5 candidate — asymmetric-taker PEPPER + alt ASH.

    ASH leg = H1 / Alt wall_mid leg. PEPPER leg = promoted leg with
    per-side taker edges (buy=1.5, sell=3.0); all other PEPPER knobs
    match promoted. Additive export; does not replace promoted / H1 /
    alt. See ``outputs/round_1/fastsearch/final_recommendation.md``.
    """
    return _round1_engine_with(
        ASH_COATED_OSMIUM=dict(
            fair_value_method="wall_mid",
            fair_value_fallbacks=("mid", "microprice"),
            maker_edge=1.5,
            taker_edge=0.5,
            inventory_skew=4.0,
            flatten_threshold=0.7,
            history_length=48,
        ),
        INTARIAN_PEPPER_ROOT=dict(
            fair_value_method="linear_drift",
            fair_value_fallbacks=("depth_mid", "hybrid_wall_micro", "mid"),
            maker_edge=1.0,
            taker_edge=2.0,
            taker_edge_buy=1.5,
            taker_edge_sell=3.0,
            inventory_skew=2.0,
            flatten_threshold=0.7,
            history_length=32,
        ),
    )


def round1_test_engine_config() -> EngineConfig:
    """Test — wall-based ASH (same as F5/H1) + buy-and-hold PEPPER.

    Directional upper-bound reference; additive; never replaces a
    shipped bundle.
    """
    return _round1_engine_with(
        ASH_COATED_OSMIUM=dict(
            fair_value_method="wall_mid",
            fair_value_fallbacks=("mid", "microprice"),
            maker_edge=1.5,
            taker_edge=0.5,
            inventory_skew=4.0,
            flatten_threshold=0.7,
            history_length=48,
        ),
        INTARIAN_PEPPER_ROOT=dict(
            strategy_name="buy_and_hold",
            fair_value_method="mid",
            fair_value_fallbacks=(),
            # Bump max_aggressive_size so one tick is enough to fill
            # the full position limit (80). Keeps the remaining
            # session truly "hold".
            max_aggressive_size=80,
        ),
    )


def round1_alt_engine_config() -> EngineConfig:
    """Phase-6 higher-upside alternate. See
    ``outputs/round_1/notes/phase5_review_shortlist.md``.
    """
    return _round1_engine_with(
        ASH_COATED_OSMIUM=dict(
            fair_value_method="wall_mid",
            fair_value_fallbacks=("mid", "microprice"),
            maker_edge=1.5,
            taker_edge=0.5,
            inventory_skew=4.0,
            flatten_threshold=0.7,
            history_length=48,
        ),
        INTARIAN_PEPPER_ROOT=dict(
            fair_value_method="linear_drift",
            fair_value_fallbacks=("depth_mid", "hybrid_wall_micro", "mid"),
            maker_edge=1.0,
            taker_edge=2.0,
            inventory_skew=1.0,
            flatten_threshold=0.9,
            history_length=32,
        ),
    )

# ========================================================================
# src/core/logger.py
# ========================================================================

class DecisionLogger:
    def __init__(self, max_events: int = 256) -> None:
        self.max_events = max_events
        self.events: list[dict[str, object]] = []

    def record(self, event: dict[str, object]) -> None:
        self.events.append(event)
        if len(self.events) > self.max_events:
            del self.events[: len(self.events) - self.max_events]

    def to_json(self, max_chars: int = 4_000) -> str:
        payload = json.dumps(self.events, separators=(",", ":"), sort_keys=True)
        if len(payload) <= max_chars:
            return payload
        return payload[: max_chars - 3] + "..."

# ========================================================================
# src/core/market_data.py
# ========================================================================

"""Raw ``TradingState`` -> canonical ``NormalizedSnapshot`` adapter.

Everything downstream of this module consumes ``NormalizedSnapshot``s, so
this is the only place that has to know how Prosperity lays out raw
order-book and trade data.

Conventions enforced here:

- Bids are sorted price-descending; asks are sorted price-ascending.
  Strategies can then rely on ``bids[0]`` being the best bid.
- Ask volumes are always returned as *positive* integers, regardless of
  whether the raw ``sell_orders`` dict uses Prosperity's negative-volume
  convention or an already-positive mirror. Zero-volume levels are
  dropped.
- Trade lists combine own and market trades and are sorted by timestamp,
  with a ``source`` tag preserved so diagnostics can distinguish them.

This module produces no orders and holds no state.
"""




class MarketDataAdapter:
    def normalize_state(self, state: TradingState) -> dict[str, NormalizedSnapshot]:
        snapshots: dict[str, NormalizedSnapshot] = {}
        for product, order_depth in state.order_depths.items():
            bids, asks = self._normalize_depth(order_depth)
            trades = self._normalize_trades(
                state.own_trades.get(product, []) if state.own_trades else [],
                state.market_trades.get(product, []) if state.market_trades else [],
            )
            snapshots[product] = NormalizedSnapshot(
                product=product,
                timestamp=state.timestamp,
                bids=bids,
                asks=asks,
                position=state.position.get(product, 0) if state.position else 0,
                trades=trades,
            )
        return snapshots

    @staticmethod
    def _normalize_depth(
        order_depth: OrderDepth,
    ) -> tuple[tuple[BookLevel, ...], tuple[BookLevel, ...]]:
        buys = getattr(order_depth, "buy_orders", {}) or {}
        sells = getattr(order_depth, "sell_orders", {}) or {}

        bids = tuple(
            BookLevel(price=int(price), volume=int(volume))
            for price, volume in sorted(buys.items(), key=lambda item: item[0], reverse=True)
            if int(volume) > 0
        )
        # Prosperity convention: sell_orders use negative volume.
        # We accept either convention and always return positive volumes.
        asks = tuple(
            BookLevel(price=int(price), volume=abs(int(volume)))
            for price, volume in sorted(sells.items(), key=lambda item: item[0])
            if int(volume) != 0
        )
        return bids, asks

    @staticmethod
    def _normalize_trades(
        own_trades: list[Trade], market_trades: list[Trade]
    ) -> tuple[TradePrint, ...]:
        combined: list[TradePrint] = []
        combined.extend(
            TradePrint(
                price=int(trade.price),
                quantity=int(trade.quantity),
                buyer=trade.buyer,
                seller=trade.seller,
                timestamp=int(trade.timestamp),
                source="own",
            )
            for trade in own_trades or []
        )
        combined.extend(
            TradePrint(
                price=int(trade.price),
                quantity=int(trade.quantity),
                buyer=trade.buyer,
                seller=trade.seller,
                timestamp=int(trade.timestamp),
                source="market",
            )
            for trade in market_trades or []
        )
        combined.sort(key=lambda trade: trade.timestamp)
        return tuple(combined)

# ========================================================================
# src/core/fair_value.py
# ========================================================================

"""Fair value estimators and the engine that resolves them.

Doctrine:

- Every trading decision must flow through a fair-value abstraction.
- Estimators are pluggable objects implementing the ``Estimator``
  protocol. New estimators register into ``ESTIMATORS``.
- Per-product resolution uses a primary estimator plus an ordered
  fallback chain (``ProductConfig.fair_value_fallbacks``). The first
  estimator in the chain that returns a non-``None`` result wins.
- ``estimate_all`` runs every registered estimator on the same snapshot
  so Phase 3 experiments can compare proxies side-by-side without
  rewriting production code.

Each estimator is stateless with respect to the request: it reads the
frozen snapshot and the product's rolling memory, and returns a
``FairValueEstimate`` or ``None`` to indicate that it cannot score this
step.
"""




_DEFAULT_EWMA_ALPHA = 0.3


class Estimator(Protocol):
    name: str

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None: ...


class AnchorEstimator:
    name = "anchor"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        if config.anchor_price is None:
            return None
        return FairValueEstimate(
            price=float(config.anchor_price),
            method=self.name,
            confidence=1.0,
            components=MappingProxyType({"anchor_price": float(config.anchor_price)}),
        )


class MidEstimator:
    name = "mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        if snapshot.mid is None:
            return None
        return FairValueEstimate(price=float(snapshot.mid), method=self.name, confidence=0.7)


class MicropriceEstimator:
    name = "microprice"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        if snapshot.microprice is None:
            return None
        components: Mapping[str, Scalar] = MappingProxyType(
            {"imbalance": float(snapshot.book_imbalance or 0.0)}
        )
        return FairValueEstimate(
            price=float(snapshot.microprice),
            method=self.name,
            confidence=0.8,
            components=components,
        )


class RollingMidEstimator:
    name = "rolling_mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        history = list(memory.recent_mids)
        if snapshot.mid is not None:
            history.append(float(snapshot.mid))
        if not history:
            return None
        return FairValueEstimate(
            price=sum(history) / len(history),
            method=self.name,
            confidence=0.65,
        )


class WeightedMidEstimator:
    """Linearly-weighted average of recent mids.

    Uses ``config.history_length`` as the lookback window so that
    parameter sweeps of ``history_length`` are meaningful.  Previously
    this was hardcoded at 4 (``LOOKBACK``), which made sweeps of
    ``history_length`` a no-op for any value >= 4.
    """

    name = "weighted_mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        lookback = config.history_length if config.history_length > 0 else 0
        history = memory.recent_mids[-lookback:] if lookback > 0 else []
        if snapshot.mid is None:
            # Fall back to pure history if the book is one-sided.
            if not history:
                return None
            weights = list(range(1, len(history) + 1))
            return FairValueEstimate(
                price=weighted_average(history, weights),
                method=self.name,
                confidence=0.55,
            )
        values = [*history, float(snapshot.mid)]
        weights = list(range(1, len(values) + 1))
        return FairValueEstimate(
            price=weighted_average(values, weights),
            method=self.name,
            confidence=0.7,
        )


class EwmaMidEstimator:
    """Exponentially weighted moving average of recent mids.

    Applies the recurrence ``ewma = alpha * m + (1 - alpha) * ewma`` over
    ``memory.recent_mids`` oldest-to-newest, seeding with the first
    available sample, and finally blends in ``snapshot.mid`` if the
    current book has one. Reads alpha from ``ProductConfig.ewma_alpha``
    and falls back to ``_DEFAULT_EWMA_ALPHA`` when unset.

    Cold-start behaviour:
    - empty history AND no current mid -> return ``None`` (let the
      fallback chain handle it).
    - empty history, current mid present -> return the current mid and
      mark ``components["bootstrap"] = 1.0`` so the review pack can see
      that the estimate was a cold-start.
    - one-sample history, no current mid -> return that sample,
      bootstrap flagged.
    - ``alpha == 1.0`` -> collapses to the current mid (verified in
      tests).
    """

    name = "ewma_mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        alpha = config.ewma_alpha if config.ewma_alpha is not None else _DEFAULT_EWMA_ALPHA
        history = memory.recent_mids
        current = snapshot.mid

        if not history and current is None:
            return None

        bootstrap = False
        if not history:
            # Cold start: no prior samples, use the current mid as seed.
            ewma = float(current)  # type: ignore[arg-type]
            bootstrap = True
        else:
            ewma = float(history[0])
            for prior_mid in history[1:]:
                ewma = alpha * float(prior_mid) + (1.0 - alpha) * ewma
            if current is None:
                # No current mid to blend in: still valid, but mark it.
                bootstrap = len(history) == 1
            else:
                ewma = alpha * float(current) + (1.0 - alpha) * ewma

        components: dict[str, Scalar] = {"alpha": float(alpha)}
        if bootstrap:
            components["bootstrap"] = 1.0
        return FairValueEstimate(
            price=ewma,
            method=self.name,
            confidence=0.72,
            components=MappingProxyType(components),
        )


class LinearDriftEstimator:
    """Online linear-drift estimator: fair = slope * index + intercept.

    Fits a simple ordinary-least-squares line over the most recent
    ``config.history_length`` mids held in ``memory.recent_mids`` (or
    all of them if ``history_length`` is 0) and projects one step
    ahead to forecast the next mid. Assumes the observations are
    evenly spaced in time (true for IMC Prosperity replay data, which
    ticks at a constant 100-timestamp cadence).

    Designed for Round 1 INTARIAN_PEPPER_ROOT, which exhibits an
    almost-deterministic +0.1 per timestamp-step drift. The estimator
    does NOT hardcode the slope; it is recovered from recent data so
    the estimator remains useful if the slope drifts.

    Cold-start behaviour:
    - 0 prior mids and no current mid -> return ``None``.
    - 0 prior mids, current mid present -> return the current mid
      marked as ``bootstrap``.
    - 1 prior mid: fall back to the most recent mid.
    - 2+ prior mids: OLS fit with index as the independent variable;
      project one index step ahead to get the next-step forecast.
    """

    name = "linear_drift"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        lookback = config.history_length if config.history_length > 0 else None
        history = list(memory.recent_mids)
        if lookback is not None:
            history = history[-lookback:]
        current = snapshot.mid

        if not history and current is None:
            return None

        # Cold-start
        if not history:
            return FairValueEstimate(
                price=float(current),  # type: ignore[arg-type]
                method=self.name,
                confidence=0.3,
                components=MappingProxyType({"bootstrap": 1.0}),
            )

        # Build (index, mid) sample set. Use history, then append the
        # current mid if we have one.
        ys: list[float] = [float(y) for y in history]
        if current is not None:
            ys.append(float(current))

        n = len(ys)
        if n < 2:
            # Not enough points for a slope: return most recent observation.
            return FairValueEstimate(
                price=ys[-1],
                method=self.name,
                confidence=0.4,
                components=MappingProxyType({"bootstrap": 1.0, "samples": float(n)}),
            )

        xs = list(range(n))
        mean_x = (n - 1) / 2.0
        mean_y = sum(ys) / n
        var_x = sum((x - mean_x) ** 2 for x in xs)
        if var_x <= 0:
            return FairValueEstimate(
                price=ys[-1],
                method=self.name,
                confidence=0.4,
                components=MappingProxyType({"samples": float(n)}),
            )
        cov_xy = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys, strict=True))
        slope = cov_xy / var_x
        intercept = mean_y - slope * mean_x
        # Project one index step ahead (= the next observation).
        forecast = slope * n + intercept

        components: dict[str, Scalar] = {
            "slope": float(slope),
            "intercept": float(intercept),
            "samples": float(n),
        }
        return FairValueEstimate(
            price=forecast,
            method=self.name,
            confidence=0.7,
            components=MappingProxyType(components),
        )


class DepthMidEstimator:
    name = "depth_mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        del memory, config
        if not snapshot.bids or not snapshot.asks:
            return None

        bid_volume = sum(level.volume for level in snapshot.bids)
        ask_volume = sum(level.volume for level in snapshot.asks)
        if bid_volume <= 0 or ask_volume <= 0:
            return None

        bid_vwap = sum(level.price * level.volume for level in snapshot.bids) / bid_volume
        ask_vwap = sum(level.price * level.volume for level in snapshot.asks) / ask_volume

        return FairValueEstimate(
            price=(bid_vwap + ask_vwap) / 2.0,
            method=self.name,
            confidence=0.75,
            components=MappingProxyType(
                {
                    "bid_vwap": bid_vwap,
                    "ask_vwap": ask_vwap,
                }
            ),
        )


class WallMidEstimator:
    """Fair value as midpoint of the largest bid and ask levels."""

    name = "wall_mid"

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        del memory, config
        if not snapshot.bids or not snapshot.asks:
            return None

        wall_bid = max(snapshot.bids, key=lambda l: l.volume)
        wall_ask = max(snapshot.asks, key=lambda l: l.volume)

        return FairValueEstimate(
            price=(wall_bid.price + wall_ask.price) / 2.0,
            method=self.name,
            confidence=0.75,
            components=MappingProxyType(
                {
                    "wall_bid_price": wall_bid.price,
                    "wall_ask_price": wall_ask.price,
                    "wall_bid_vol": wall_bid.volume,
                    "wall_ask_vol": wall_ask.volume,
                }
            ),
        )


class FilteredWallMidEstimator:
    """Wall mid after filtering out small levels.

    Considers only the top N visible levels per side. Filters out levels
    with volume < 25% of the side's max volume. Among survivors, picks
    the largest volume; ties broken by closeness to touch.
    """

    name = "filtered_wall_mid"
    _TOP_N = 3
    _MIN_VOLUME_RATIO = 0.25

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        del memory, config
        if not snapshot.bids or not snapshot.asks:
            return None

        top_bids = snapshot.bids[: self._TOP_N]
        top_asks = snapshot.asks[: self._TOP_N]

        wall_bid, bid_filtered = self._pick_wall(top_bids)
        wall_ask, ask_filtered = self._pick_wall(top_asks)

        if wall_bid is None or wall_ask is None:
            return None

        return FairValueEstimate(
            price=(wall_bid.price + wall_ask.price) / 2.0,
            method=self.name,
            confidence=0.75,
            components=MappingProxyType(
                {
                    "wall_bid_price": wall_bid.price,
                    "wall_ask_price": wall_ask.price,
                    "filtered_out_count": bid_filtered + ask_filtered,
                }
            ),
        )

    @staticmethod
    def _pick_wall(levels: tuple[BookLevel, ...]) -> tuple[BookLevel | None, int]:
        """Select the wall level after filtering.

        Returns (selected_level, count_filtered_out).
        """
        if not levels:
            return None, 0
        max_vol = max(l.volume for l in levels)
        threshold = max_vol * FilteredWallMidEstimator._MIN_VOLUME_RATIO
        indexed = [(i, l) for i, l in enumerate(levels) if l.volume >= threshold]
        filtered_count = len(levels) - len(indexed)
        if not indexed:
            return None, filtered_count
        # Largest volume first, then closest to touch (smallest index)
        indexed.sort(key=lambda x: (-x[1].volume, x[0]))
        return indexed[0][1], filtered_count


class HybridWallMicroEstimator:
    """Blends wall_mid and microprice estimates."""

    name = "hybrid_wall_micro"
    wall_weight: float = 0.5

    def __init__(self) -> None:
        self._wall = WallMidEstimator()
        self._micro = MicropriceEstimator()

    def estimate(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate | None:
        wall_est = self._wall.estimate(snapshot, memory, config)
        micro_est = self._micro.estimate(snapshot, memory, config)

        if wall_est is not None and micro_est is not None:
            price = self.wall_weight * wall_est.price + (1 - self.wall_weight) * micro_est.price
            return FairValueEstimate(
                price=price,
                method=self.name,
                confidence=0.75,
                components=MappingProxyType(
                    {
                        "wall_mid_price": wall_est.price,
                        "microprice": micro_est.price,
                        "wall_weight": self.wall_weight,
                    }
                ),
            )

        if wall_est is not None:
            return FairValueEstimate(
                price=wall_est.price,
                method=self.name,
                confidence=0.75,
                components=MappingProxyType(
                    {"wall_mid_price": wall_est.price, "wall_weight": 1.0}
                ),
            )

        if micro_est is not None:
            return FairValueEstimate(
                price=micro_est.price,
                method=self.name,
                confidence=0.75,
                components=MappingProxyType(
                    {"microprice": micro_est.price, "wall_weight": 0.0}
                ),
            )

        return None


ESTIMATORS: Mapping[str, Estimator] = MappingProxyType(
    {
        "anchor": AnchorEstimator(),
        "mid": MidEstimator(),
        "microprice": MicropriceEstimator(),
        "rolling_mid": RollingMidEstimator(),
        "weighted_mid": WeightedMidEstimator(),
        "ewma_mid": EwmaMidEstimator(),
        "linear_drift": LinearDriftEstimator(),
        "depth_mid": DepthMidEstimator(),
        "wall_mid": WallMidEstimator(),
        "filtered_wall_mid": FilteredWallMidEstimator(),
        "hybrid_wall_micro": HybridWallMicroEstimator(),
    }
)


class FairValueEngine:
    """Resolves fair-value estimates with a per-product fallback chain."""

    def __init__(self, estimators: Mapping[str, Estimator] | None = None) -> None:
        self._estimators: dict[str, Estimator] = dict(estimators or ESTIMATORS)

    def register(self, estimator: Estimator) -> None:
        self._estimators[estimator.name] = estimator

    def known_estimators(self) -> tuple[str, ...]:
        return tuple(sorted(self._estimators))

    def estimate(
        self,
        product: str,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> FairValueEstimate:
        """Resolve the primary + fallback chain; never returns ``None``.

        If every configured estimator declines, drop to an anchor-price
        fallback, and finally a zero-confidence zero-price marker so the
        caller can still proceed. The doctrine Invariant 5: a fallback
        path always exists.

        **Warning — ``zero_fallback`` is a trap for products without an
        ``anchor_price``.** The ``price=0.0`` marker exists so the
        trader never crashes when the book is empty, but if any
        strategy uses that value as a real fair value it will place
        catastrophically mispriced orders. Round-1 sweeps caught this:
        ``depth_mid`` / ``hybrid_wall_micro`` / ``mid`` primaries on
        INTARIAN_PEPPER_ROOT (no anchor_price) all hit ``zero_fallback``
        on one-sided books and posted ~-128k PnL. The fix for any
        production-ready ``ProductConfig`` without an anchor is to put
        at least one estimator that **always returns a value** (e.g.
        ``linear_drift`` after warm-up, or any estimator with a
        non-``None`` bootstrap branch) at the end of the fallback
        chain. See ``outputs/round_1/notes/phase4_sweep_shortlist.md``
        for the full diagnosis.
        """
        del product  # reserved for future per-product registries
        chain: list[str] = [config.fair_value_method, *config.fair_value_fallbacks]
        for name in chain:
            estimator = self._estimators.get(name)
            if estimator is None:
                continue
            result = estimator.estimate(snapshot, memory, config)
            if result is not None:
                return result
        if config.anchor_price is not None:
            return FairValueEstimate(
                price=float(config.anchor_price),
                method="anchor_fallback",
                confidence=0.1,
            )
        return FairValueEstimate(price=0.0, method="zero_fallback", confidence=0.0)

    def estimate_all(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        config: ProductConfig,
    ) -> dict[str, FairValueEstimate]:
        """Run every registered estimator on the same snapshot.

        Skips estimators that return ``None``. Useful for Phase 3
        side-by-side fair-value inference experiments.
        """
        results: dict[str, FairValueEstimate] = {}
        for name, estimator in self._estimators.items():
            result = estimator.estimate(snapshot, memory, config)
            if result is not None:
                results[name] = result
        return results

# ========================================================================
# src/core/state_store.py
# ========================================================================

"""Versioned persistence for the trader's rolling ``EngineState``.

Prosperity calls ``Trader.run()`` in an effectively stateless container.
Anything we want to remember across iterations must live in ``traderData``,
which is a string with a hard 50,000 character budget.

This module is the single authoritative boundary between ``EngineState``
(the in-memory dataclass the engine works with) and the opaque string we
hand back to the platform.

Guarantees:
- ``load()`` never raises on empty, ``None``, or malformed input. It falls
  back to a fresh ``EngineState`` with the current version.
- ``save()`` always returns a string whose length is ``<= max_chars``.
- Schema migration hook ``_migrate`` is called when the stored version is
  older than the current version. Today it is a no-op, but the plumbing is
  in place so strategy history survives a version bump.
- Persisted history lists are clamped at load time so an adversarial or
  accidentally-bloated ``traderData`` cannot grow unbounded after a restart.
"""




_MAX_PERSISTED_HISTORY = 64
_TRUNCATED_HISTORY_KEEP = 8


class StateStore:
    def __init__(
        self,
        version: int = 1,
        max_chars: int = 50_000,
        max_history: int = _MAX_PERSISTED_HISTORY,
        truncated_history_keep: int = _TRUNCATED_HISTORY_KEEP,
    ) -> None:
        if version < 1:
            raise ValueError("version must be >= 1")
        if max_chars <= 0:
            raise ValueError("max_chars must be > 0")
        if max_history < 0 or truncated_history_keep < 0:
            raise ValueError("history bounds must be >= 0")
        if truncated_history_keep > max_history:
            raise ValueError("truncated_history_keep must be <= max_history")

        self.version = version
        self.max_chars = max_chars
        self.max_history = max_history
        self.truncated_history_keep = truncated_history_keep

    # ------------------------------------------------------------------ load

    def load(self, trader_data: str | None) -> EngineState:
        """Parse ``traderData`` into an ``EngineState``.

        Returns a fresh state on any failure mode. This is intentional:
        a corrupted state blob must never crash ``Trader.run()``.
        """
        if not trader_data:
            return EngineState(version=self.version)

        try:
            raw = json.loads(trader_data)
        except (TypeError, ValueError):
            return EngineState(version=self.version)

        if not isinstance(raw, dict):
            return EngineState(version=self.version)

        stored_version = self._safe_int(raw.get("version"), default=self.version)
        if stored_version != self.version:
            raw = self._migrate(raw, from_version=stored_version)

        state = EngineState(version=self.version)
        raw_products = raw.get("products", {})
        if not isinstance(raw_products, dict):
            return state

        for product, payload in raw_products.items():
            if not isinstance(product, str) or not isinstance(payload, dict):
                continue
            state.products[product] = ProductMemory(
                recent_mids=self._coerce_float_list(payload.get("recent_mids")),
                recent_spreads=self._coerce_float_list(payload.get("recent_spreads")),
                counters=self._coerce_int_dict(payload.get("counters")),
                flags=self._coerce_bool_dict(payload.get("flags")),
                values=self._coerce_float_dict(payload.get("values")),
            )

        return state

    # ------------------------------------------------------------------ save

    def save(self, state: EngineState) -> str:
        """Serialize ``state`` to a platform-safe string.

        Strategy:
        1. Full encode with current contents.
        2. If too big, encode a truncated version with the most recent
           ``truncated_history_keep`` mids/spreads only.
        3. If still too big, drop all product memory and return an
           empty-products marker.

        ``_encode`` uses ``allow_nan=False`` so NaN/Infinity leaking
        into ``ProductMemory.values`` cannot produce spec-violating
        JSON that Prosperity's parser would silently reject. If it
        raises, we drop all memory rather than returning a bad blob.
        """
        try:
            payload = asdict(state)
            payload["version"] = self.version

            encoded = self._encode(payload)
            if len(encoded) <= self.max_chars:
                return encoded

            compact: dict[str, Any] = {"version": self.version, "products": {}}
            for product, memory in state.products.items():
                compact["products"][product] = {
                    "recent_mids": memory.recent_mids[-self.truncated_history_keep :],
                    "recent_spreads": memory.recent_spreads[-self.truncated_history_keep :],
                    "counters": memory.counters,
                    "flags": memory.flags,
                    "values": memory.values,
                }
            encoded = self._encode(compact)
            if len(encoded) <= self.max_chars:
                return encoded
        except ValueError:
            warnings.warn(
                "StateStore.save refused to emit non-finite values "
                "(NaN/Infinity) and dropped all product memory for this "
                "iteration. Investigate which strategy wrote the bad value.",
                RuntimeWarning,
                stacklevel=2,
            )

        return self._encode({"version": self.version, "products": {}})

    # -------------------------------------------------------------- migrate

    def _migrate(self, raw: dict[str, Any], *, from_version: int) -> dict[str, Any]:
        """Hook for future schema migrations.

        The base implementation is a no-op and warns loudly when called
        with a mismatched ``from_version``. Subclasses should override
        this to dispatch on ``from_version`` and silently perform
        whatever rewrites the new schema needs.
        """
        if from_version != self.version:
            warnings.warn(
                f"StateStore._migrate invoked with from_version={from_version} "
                f"(current={self.version}) but the base implementation is a no-op. "
                "Override _migrate or bump the schema carefully.",
                UserWarning,
                stacklevel=2,
            )
        return raw

    # ---------------------------------------------------------------- utils

    @staticmethod
    def _encode(payload: dict[str, Any]) -> str:
        return json.dumps(payload, separators=(",", ":"), sort_keys=True, allow_nan=False)

    @staticmethod
    def _safe_int(value: Any, default: int) -> int:
        try:
            return int(value)
        except (TypeError, ValueError):
            return default

    def _coerce_float_list(self, value: Any) -> list[float]:
        if not isinstance(value, list):
            return []
        coerced = [
            float(item)
            for item in value
            if isinstance(item, (int, float)) and not isinstance(item, bool)
        ]
        if len(coerced) > self.max_history:
            coerced = coerced[-self.max_history :]
        return coerced

    @staticmethod
    def _coerce_int_dict(value: Any) -> dict[str, int]:
        if not isinstance(value, dict):
            return {}
        out: dict[str, int] = {}
        for key, item in value.items():
            if isinstance(item, bool):
                continue
            if isinstance(item, (int, float)):
                out[str(key)] = int(item)
        return out

    @staticmethod
    def _coerce_bool_dict(value: Any) -> dict[str, bool]:
        if not isinstance(value, dict):
            return {}
        out: dict[str, bool] = {}
        for key, item in value.items():
            if isinstance(item, bool):
                out[str(key)] = item
        return out

    @staticmethod
    def _coerce_float_dict(value: Any) -> dict[str, float]:
        if not isinstance(value, dict):
            return {}
        out: dict[str, float] = {}
        for key, item in value.items():
            if isinstance(item, bool):
                continue
            if isinstance(item, (int, float)):
                out[str(key)] = float(item)
        return out

# ========================================================================
# src/signals/__init__.py
# ========================================================================

"""Signal scanning and flow analysis framework."""

# ========================================================================
# src/signals/flow_analyzer.py
# ========================================================================

"""Generic trade-flow pattern detection framework.

This module is an **observational** layer. It detects patterns in the
market trade tape (repeated sizes, directional flow, trades near local
extrema) and returns an ephemeral ``FlowReport``. It never alters
strategy behaviour, fair-value estimates, or execution decisions.

Persisted state (via ``ProductMemory``) is kept to the absolute minimum
needed for cross-call continuity:

- ``values["scan_flow_score"]`` — decayed directional score in [-1, 1].
- ``counters["scan_step_count"]`` — number of steps the scanner has run.

Extrema (high / low) are derived from ``memory.recent_mids`` each step
and are **not** persisted.

Net-flow convention (heuristic, not true aggressor inference):
- Trade with only ``buyer`` populated → +quantity (buy pressure proxy).
- Trade with only ``seller`` populated -> -quantity (sell pressure proxy).
- Trade with both or neither → 0 (ambiguous, excluded from flow).
"""




# ---------------------------------------------------------------- keys

_KEY_FLOW_SCORE = "scan_flow_score"
_KEY_STEP_COUNT = "scan_step_count"


class FlowAnalyzer:
    """Stateless scanner — all mutable state lives in ``ProductMemory``."""

    def __init__(self, config: ScannerConfig) -> None:
        self.config = config

    # -------------------------------------------------------------- public

    def scan(
        self,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
    ) -> FlowReport | None:
        """Analyse the current step's trade tape and return a report.

        Returns ``None`` when the scanner is disabled so the caller can
        skip any downstream logging unconditionally.
        """
        if not self.config.enabled:
            return None

        market_trades = tuple(t for t in snapshot.trades if t.source == "market")

        repeated_sizes = _count_sizes(market_trades)
        net_flow = _compute_net_flow(market_trades)
        total_volume = sum(t.quantity for t in market_trades) or 1

        old_score = memory.values.get(_KEY_FLOW_SCORE, 0.0)
        normalised = max(-1.0, min(1.0, net_flow / total_volume))
        new_score = self.config.flow_decay * old_score + (1.0 - self.config.flow_decay) * normalised
        new_score = max(-1.0, min(1.0, new_score))

        recent_high, recent_low = _derive_extrema(memory.recent_mids, self.config.extrema_window)
        near_high = _any_near(market_trades, recent_high, self.config.extrema_tolerance)
        near_low = _any_near(market_trades, recent_low, self.config.extrema_tolerance)

        flags = _build_flags(
            repeated_sizes=repeated_sizes,
            flow_score=new_score,
            near_high=near_high,
            near_low=near_low,
            threshold=self.config.repeated_size_threshold,
        )

        # Persist minimal state -------------------------------------------
        memory.values[_KEY_FLOW_SCORE] = new_score
        memory.counters[_KEY_STEP_COUNT] = memory.counters.get(_KEY_STEP_COUNT, 0) + 1

        return FlowReport(
            product=snapshot.product,
            timestamp=snapshot.timestamp,
            repeated_sizes=MappingProxyType(repeated_sizes),
            net_flow=net_flow,
            flow_score=round(new_score, 6),
            near_high=near_high,
            near_low=near_low,
            flags=flags,
            metadata=MappingProxyType(
                {
                    "market_trade_count": len(market_trades),
                    "total_volume": total_volume,
                }
            ),
        )


# -------------------------------------------------------------- helpers


def _count_sizes(trades: tuple[TradePrint, ...]) -> dict[int, int]:
    """Count how many times each trade quantity appears."""
    return dict(Counter(t.quantity for t in trades))


def _compute_net_flow(trades: tuple[TradePrint, ...]) -> int:
    """Heuristic signed net volume.

    This is a *proxy* for directional pressure — it does not claim to
    infer the true aggressor side. The convention is intentionally
    conservative: ambiguous trades (both buyer and seller populated, or
    neither) contribute zero.
    """
    net = 0
    for t in trades:
        has_buyer = t.buyer is not None and t.buyer != ""
        has_seller = t.seller is not None and t.seller != ""
        if has_buyer and not has_seller:
            net += t.quantity
        elif has_seller and not has_buyer:
            net -= t.quantity
        # both or neither → ambiguous, skip
    return net


def _derive_extrema(recent_mids: list[float], window: int) -> tuple[float | None, float | None]:
    """Return (high, low) from the last *window* mid prices, or None."""
    if not recent_mids:
        return None, None
    tail = recent_mids[-window:] if window > 0 else recent_mids
    return max(tail), min(tail)


def _any_near(
    trades: tuple[TradePrint, ...],
    level: float | None,
    tolerance: float,
) -> bool:
    """True if any trade price is within *tolerance* of *level*."""
    if level is None or not trades:
        return False
    return any(abs(t.price - level) <= tolerance for t in trades)


def _build_flags(
    *,
    repeated_sizes: dict[int, int],
    flow_score: float,
    near_high: bool,
    near_low: bool,
    threshold: int,
) -> tuple[str, ...]:
    """Build a tuple of human-readable pattern labels."""
    flags: list[str] = []

    for qty, count in sorted(repeated_sizes.items()):
        if count >= threshold:
            flags.append(f"repeated_size_{qty}x{count}")

    if flow_score > 0.5:
        flags.append("buy_pressure")
    elif flow_score < -0.5:
        flags.append("sell_pressure")

    if near_high:
        flags.append("near_local_high")
    if near_low:
        flags.append("near_local_low")

    return tuple(flags)

# ========================================================================
# src/core/signals.py
# ========================================================================

"""Translate fair value + snapshot + config into a trading intent.

This module converts "what do we believe" (the fair value estimate)
into "what would we want to do about it" (a ``SignalIntent`` naming
taker thresholds, maker prices, and the execution mode). It deliberately
does NOT emit ``Order``s — that's the execution engine's job.

Capacity recovery rule:
- When ``|position / limit| >= flatten_threshold`` the engine enters
  "recovery" mode. It stops adding to the side that already has
  exposure and tightens the opposite side toward fair value.
- In practice that means a long position disables buy intent entirely
  (maker bid size = 0 AND taker ``buy_below`` is set to ``None``) and
  pulls the maker ask in to fair value so inventory unwinds fastest.

Phase-9 early-window extensions:
- ``early_window`` gates the "early" branches by ``snapshot.timestamp``.
- When set, ``taker_edge_buy`` / ``taker_edge_sell`` split the normally
  symmetric taker threshold (useful when the day has a directional
  drift). Their ``early_*`` siblings only apply in the early window.
- ``early_short_cap`` blocks sell intent entirely while short inventory
  is at or below the cap (Family 2 — hard first-half short guard).
- ``early_short_skew_mult`` + ``early_short_flatten`` give a stricter
  recovery profile while short during the early window (Family 4).

All Phase-9 knobs default to neutral values. With defaults, this
module's output is byte-identical to the Phase-8 behavior.
"""





def _effective_taker_edges(
    config: ProductConfig,
    *,
    in_early_window: bool,
) -> tuple[float, float]:
    """Resolve (buy_edge, sell_edge) with per-side / early overrides.

    Resolution order per side:
    1. If in the early window and the ``early_taker_edge_<side>`` is set,
       use it.
    2. Else if the full-day ``taker_edge_<side>`` is set, use it.
    3. Else fall back to the symmetric ``taker_edge``.
    """
    buy = config.taker_edge_buy if config.taker_edge_buy is not None else config.taker_edge
    sell = config.taker_edge_sell if config.taker_edge_sell is not None else config.taker_edge
    if in_early_window:
        if config.early_taker_edge_buy is not None:
            buy = config.early_taker_edge_buy
        if config.early_taker_edge_sell is not None:
            sell = config.early_taker_edge_sell
    return buy, sell


class SignalEngine:
    def build_market_making_intent(
        self,
        product: str,
        snapshot: NormalizedSnapshot,
        fair_value: FairValueEstimate,
        config: ProductConfig,
    ) -> SignalIntent:
        in_early_window = (
            config.early_window > 0 and snapshot.timestamp < config.early_window
        )
        buy_taker_edge, sell_taker_edge = _effective_taker_edges(
            config, in_early_window=in_early_window
        )

        position_ratio = snapshot.position / config.position_limit if config.position_limit else 0.0

        # Skew normally scales linearly with inventory ratio. In the
        # early window while short we can amplify (Family 4) to pull
        # back toward flat faster.
        skew_multiplier = 1.0
        if in_early_window and snapshot.position < 0 and config.early_short_skew_mult != 1.0:
            skew_multiplier = config.early_short_skew_mult
        skew = position_ratio * config.inventory_skew * skew_multiplier

        # Flatten threshold: allow a stricter short-side flatten during
        # the early window (Family 4). Long side and non-early behavior
        # are unchanged.
        effective_flatten = config.flatten_threshold
        if (
            in_early_window
            and snapshot.position < 0
            and config.early_short_flatten is not None
        ):
            effective_flatten = config.early_short_flatten
        flattening = abs(position_ratio) >= effective_flatten

        buy_below: float | None = fair_value.price - buy_taker_edge - skew
        sell_above: float | None = fair_value.price + sell_taker_edge - skew

        raw_bid = math.floor(fair_value.price - config.maker_edge - skew)
        raw_ask = math.ceil(fair_value.price + config.maker_edge - skew)

        if snapshot.best_ask is not None:
            raw_bid = min(raw_bid, snapshot.best_ask.price - config.tick_size)
        if snapshot.best_bid is not None:
            raw_ask = max(raw_ask, snapshot.best_bid.price + config.tick_size)

        bid_size = config.quote_size
        ask_size = config.quote_size
        mode: ExecutionMode = "hybrid"
        rationale = "market_make_around_fair_value"

        if flattening:
            mode = "recovery"
            rationale = "inventory_recovery"
            if snapshot.position > 0:
                # Long: stop buying entirely, pull ask toward fair value.
                bid_size = 0
                buy_below = None
                raw_ask = min(raw_ask, math.floor(fair_value.price))
            elif snapshot.position < 0:
                # Short: stop selling entirely, pull bid toward fair value.
                ask_size = 0
                sell_above = None
                raw_bid = max(raw_bid, math.ceil(fair_value.price))

        # Family 2 — early short-cap. Enforced *after* normal recovery
        # so we don't fight the recovery logic when the position is
        # already above the cap. Effect: once the net short has reached
        # the cap inside the early window, both taker-sell and maker-
        # ask are disabled until the cap is no longer breached (either
        # time passes out of the early window or inventory recovers).
        if (
            in_early_window
            and config.early_short_cap is not None
            and snapshot.position <= config.early_short_cap
        ):
            sell_above = None
            ask_size = 0
            if mode != "recovery":
                mode = "recovery"
                rationale = "early_short_cap"

        quote = QuoteIntent(
            bid_price=raw_bid if bid_size > 0 else None,
            bid_size=bid_size,
            ask_price=raw_ask if ask_size > 0 else None,
            ask_size=ask_size,
        )

        return SignalIntent(
            product=product,
            fair_value=fair_value,
            mode=mode,
            buy_below=buy_below,
            sell_above=sell_above,
            quote=quote,
            rationale=rationale,
            metadata={
                "position_ratio": round(position_ratio, 4),
                "skew": round(skew, 4),
                "flattening": flattening,
                "in_early_window": in_early_window,
            },
        )

# ========================================================================
# src/core/execution.py
# ========================================================================

class ExecutionEngine:
    def generate_orders(
        self,
        snapshot: NormalizedSnapshot,
        intent: SignalIntent,
        config: ProductConfig,
    ) -> list[Order]:
        orders: list[Order] = []

        remaining_buy = config.max_aggressive_size
        remaining_sell = config.max_aggressive_size

        if intent.buy_below is not None:
            for ask in snapshot.asks:
                if ask.price > intent.buy_below or remaining_buy <= 0:
                    break
                quantity = min(ask.volume, remaining_buy)
                if quantity > 0:
                    orders.append(Order(snapshot.product, ask.price, quantity))
                    remaining_buy -= quantity

        if intent.sell_above is not None:
            for bid in snapshot.bids:
                if bid.price < intent.sell_above or remaining_sell <= 0:
                    break
                quantity = min(bid.volume, remaining_sell)
                if quantity > 0:
                    orders.append(Order(snapshot.product, bid.price, -quantity))
                    remaining_sell -= quantity

        if intent.quote is not None:
            if intent.quote.bid_price is not None and intent.quote.bid_size > 0:
                orders.append(
                    Order(snapshot.product, intent.quote.bid_price, intent.quote.bid_size)
                )
            if intent.quote.ask_price is not None and intent.quote.ask_size > 0:
                orders.append(
                    Order(snapshot.product, intent.quote.ask_price, -intent.quote.ask_size)
                )

        return orders

# ========================================================================
# src/core/risk.py
# ========================================================================

"""Per-product position legality and clipping.

This is the single place where we enforce Prosperity's hard position
limits. Strategies must never assume their orders are final: the risk
manager always owns the decision about what quantity actually leaves the
trader.

The clipping model:
- We compute remaining buy and sell capacity from the current position
  and the product's limit.
- We walk through the strategy's orders in submission order, reducing
  each to fit the remaining capacity on that side.
- Orders that would have zero quantity after clipping are dropped.
- Zero-quantity input orders are silently dropped.
- An order whose ``symbol`` does not match the product being clipped is
  a programming error and raises ``ValueError`` immediately.

The rationale for clipping per-side instead of per-order is that
Prosperity will reject an entire side if the aggregate would breach the
limit. By aggregating capacity here, we make the exchange reject nothing.
"""





@dataclass(frozen=True)
class Capacity:
    buy: int
    sell: int


class RiskManager:
    @staticmethod
    def remaining_buy_capacity(position: int, limit: int) -> int:
        if limit < 0:
            raise ValueError("limit must be >= 0")
        return max(0, limit - position)

    @staticmethod
    def remaining_sell_capacity(position: int, limit: int) -> int:
        if limit < 0:
            raise ValueError("limit must be >= 0")
        return max(0, limit + position)

    @classmethod
    def capacity(cls, position: int, limit: int) -> Capacity:
        return Capacity(
            buy=cls.remaining_buy_capacity(position, limit),
            sell=cls.remaining_sell_capacity(position, limit),
        )

    @staticmethod
    def inventory_ratio(position: int, limit: int) -> float:
        if limit <= 0:
            return 0.0
        return position / limit

    def clip_orders(
        self,
        product: str,
        orders: list[Order],
        current_position: int,
        limit: int,
    ) -> list[Order]:
        if limit < 0:
            raise ValueError("limit must be >= 0")

        buy_capacity = self.remaining_buy_capacity(current_position, limit)
        sell_capacity = self.remaining_sell_capacity(current_position, limit)
        clipped: list[Order] = []

        for order in orders:
            if order.symbol != product:
                raise ValueError(
                    f"risk.clip_orders: order symbol {order.symbol!r} does not "
                    f"match product {product!r}"
                )
            if order.quantity == 0:
                continue

            if order.quantity > 0:
                quantity = min(order.quantity, buy_capacity)
                if quantity > 0:
                    clipped.append(Order(order.symbol, order.price, quantity))
                    buy_capacity -= quantity
            else:
                quantity = min(-order.quantity, sell_capacity)
                if quantity > 0:
                    clipped.append(Order(order.symbol, order.price, -quantity))
                    sell_capacity -= quantity

        return clipped

# ========================================================================
# src/core/residual.py
# ========================================================================

"""Optional residual capacity utilizer (framework-only, ships disabled).

After the main strategy emits orders, there is often unused position
budget on one or both sides.  This module inspects the leftover capacity
and optionally appends small passive maker orders to capture spread from
the residual room.

Hard rules enforced here:

1. **Maker-only** -- residual orders never cross the spread.
2. **No duplicate prices** -- if the main strategy already placed an
   order on the same side at the exact price the residual would use,
   the residual order on that side is suppressed.
3. **Post-processing only, zero coupling** -- the module receives the
   main strategy's raw order list as read-only input and appends to it.
   It never modifies existing orders, never reads or writes strategy /
   signal / fair-value state.
4. **Default disabled** -- ``ResidualConfig.enabled`` is ``False``.
   The enablement gate (PnL, trade count, maker/taker mix, markouts,
   time-near-limits comparison) must pass before the flag is flipped.

Design:
- Runs after ``ExecutionEngine.generate_orders()`` and before
  ``RiskManager.clip_orders()``.
- The risk manager still clips the combined list, so this module
  cannot breach position limits.
"""





class ResidualAllocator:
    """Append small passive orders into unused position capacity."""

    def __init__(self, config: ResidualConfig) -> None:
        self._config = config

    def augment_orders(
        self,
        *,
        product: str,
        orders: list[Order],
        snapshot: NormalizedSnapshot,
        fair_value: float,
        position: int,
        limit: int,
        mode: ExecutionMode = "maker",
    ) -> list[Order]:
        """Return *orders* with optional residual orders appended.

        If the module is disabled or the strategy is in recovery mode,
        returns the input list unchanged.
        """
        if not self._config.enabled:
            return orders

        # Never add residual orders during recovery (flattening).
        if mode == "recovery":
            return orders

        buy_capacity = max(0, limit - position)
        sell_capacity = max(0, limit + position)

        # Subtract capacity already consumed by main orders.
        # Also collect main-strategy prices per side for duplicate guard.
        main_bid_prices: set[int] = set()
        main_ask_prices: set[int] = set()

        for order in orders:
            if order.quantity > 0:
                buy_capacity -= order.quantity
                main_bid_prices.add(order.price)
            elif order.quantity < 0:
                sell_capacity -= abs(order.quantity)
                main_ask_prices.add(order.price)

        buy_capacity = max(0, buy_capacity)
        sell_capacity = max(0, sell_capacity)

        residual_orders: list[Order] = []

        if buy_capacity > 0:
            bid_price = math.floor(fair_value - self._config.residual_edge)
            bid_size = min(self._config.residual_size, buy_capacity)

            # Spread guard: suppress if bid would cross or touch best ask.
            best_ask = snapshot.best_ask
            crosses_spread = best_ask is not None and bid_price >= best_ask.price

            # Duplicate-price guard.
            duplicates_main = bid_price in main_bid_prices

            if bid_size > 0 and not crosses_spread and not duplicates_main:
                residual_orders.append(Order(product, bid_price, bid_size))

        if sell_capacity > 0:
            ask_price = math.ceil(fair_value + self._config.residual_edge)
            ask_size = min(self._config.residual_size, sell_capacity)

            # Spread guard: suppress if ask would cross or touch best bid.
            best_bid = snapshot.best_bid
            crosses_spread = best_bid is not None and ask_price <= best_bid.price

            # Duplicate-price guard.
            duplicates_main = ask_price in main_ask_prices

            if ask_size > 0 and not crosses_spread and not duplicates_main:
                residual_orders.append(Order(product, ask_price, -ask_size))

        if not residual_orders:
            return orders

        return [*orders, *residual_orders]

# ========================================================================
# src/strategies/base.py
# ========================================================================

@dataclass(frozen=True)
class StrategyContext:
    product: str
    snapshot: NormalizedSnapshot
    memory: ProductMemory
    config: ProductConfig


class BaseStrategy(ABC):
    @abstractmethod
    def generate_intent(self, context: StrategyContext) -> SignalIntent:
        raise NotImplementedError

# ========================================================================
# src/strategies/market_making.py
# ========================================================================

"""Single market-making strategy shared across products.

This is the only strategy in the engine today. It combines:

1. a fair-value estimate from ``FairValueEngine`` (which may be an
   anchor, mid, microprice, rolling or weighted mid depending on the
   product's config), and
2. a market-making intent from ``SignalEngine`` built around that
   fair value.

Different products tune *how* this strategy behaves via
``ProductConfig`` (edge widths, quote sizes, flatten thresholds) and
*which* fair-value estimator runs (``fair_value_method`` +
``fair_value_fallbacks``). A second strategy module only exists once
there is a genuinely different decision rule that cannot be reduced to
config.
"""




class MarketMakingStrategy(BaseStrategy):
    def __init__(self, fair_value_engine: FairValueEngine, signal_engine: SignalEngine) -> None:
        self.fair_value_engine = fair_value_engine
        self.signal_engine = signal_engine

    def generate_intent(self, context: StrategyContext) -> SignalIntent:
        fair_value = self.fair_value_engine.estimate(
            context.product, context.snapshot, context.memory, context.config
        )
        return self.signal_engine.build_market_making_intent(
            context.product, context.snapshot, fair_value, context.config
        )

# ========================================================================
# src/strategies/buy_and_hold.py
# ========================================================================

"""Buy-and-hold: take any ask up to the position limit, never sell.

Used by ``round1_test_engine_config`` only. RiskManager caps buys at
``position_limit - position`` so the bot holds once full.
"""



_TAKE_ANY_ASK: float = 1e9


class BuyAndHoldStrategy(BaseStrategy):
    def __init__(
        self,
        fair_value_engine: FairValueEngine | None = None,
        signal_engine: SignalEngine | None = None,
    ) -> None:
        del fair_value_engine, signal_engine

    def generate_intent(self, context: StrategyContext) -> SignalIntent:
        mid = context.snapshot.mid if context.snapshot.mid is not None else 0.0
        return SignalIntent(
            product=context.product,
            fair_value=FairValueEstimate(price=mid, method="buy_and_hold"),
            mode="taker",
            buy_below=_TAKE_ANY_ASK,
            sell_above=None,
            quote=QuoteIntent(bid_price=None, bid_size=0, ask_price=None, ask_size=0),
            rationale="buy_and_hold",
        )

# ========================================================================
# src/strategies/__init__.py
# ========================================================================

"""Strategy registry.

Product configs reference a strategy by name (``ProductConfig.strategy_name``)
and the ``Trader`` looks up that name in ``STRATEGY_REGISTRY`` to
construct the strategy instance.

Adding a new strategy means:

1. implement a subclass of ``BaseStrategy`` in a new module,
2. register it here under a unique name,
3. set ``ProductConfig.strategy_name`` on the products that should use
   it.

No changes to ``Trader.__init__`` are needed for new products that
reuse an existing strategy.
"""




StrategyFactory = Callable[[FairValueEngine, SignalEngine], BaseStrategy]

STRATEGY_REGISTRY: Mapping[str, StrategyFactory] = MappingProxyType(
    {
        "market_making": MarketMakingStrategy,
        "buy_and_hold": BuyAndHoldStrategy,
    }
)

__all__ = [
    "STRATEGY_REGISTRY",
    "BaseStrategy",
    "BuyAndHoldStrategy",
    "MarketMakingStrategy",
    "StrategyFactory",
]

# ========================================================================
# src/trader.py
# ========================================================================

"""Entrypoint for the Prosperity live trading container.

Responsibilities of this file are deliberately narrow:

1. Restore persistent state from ``state.traderData``.
2. Normalize the incoming ``TradingState`` into canonical snapshots.
3. Dispatch each known product to its configured strategy via the
   ``STRATEGY_REGISTRY`` in ``src/strategies/``.
4. Route the strategy's intent through execution and risk layers.
5. Update rolling per-product memory.
6. Serialize next-iteration state back into ``traderData``.
7. Return ``(orders, conversions, traderData)``.

This file never contains product-specific pricing or execution
heuristics. Those live in ``strategies/`` and ``core/``.

Safety: ``run()`` is wrapped in a top-level safety net. If any
downstream module raises, the trader returns an empty orders dict and
preserves the previous ``traderData`` so the Prosperity container does
not crash. Tests can set ``_reraise_exceptions=True`` to opt out and
surface errors.
"""




_LOG = logging.getLogger(__name__)


class Trader:
    def __init__(
        self,
        config: EngineConfig | None = None,
        *,
        reraise_exceptions: bool = False,
    ) -> None:
        self.config = config or round1_test_engine_config()
        self.state_store = StateStore(
            version=self.config.state_version,
            max_chars=self.config.max_trader_data_chars,
        )
        self.market_data = MarketDataAdapter()
        self.fair_value_engine = FairValueEngine()
        self.signal_engine = SignalEngine()
        self.execution_engine = ExecutionEngine()
        self.risk_manager = RiskManager()
        self.residual_allocator = ResidualAllocator(self.config.residual_config)
        self.flow_analyzer = FlowAnalyzer(self.config.scanner_config)
        self.logger = DecisionLogger()
        self._reraise_exceptions = reraise_exceptions
        self.strategies: dict[str, BaseStrategy] = self._build_strategies()

    # ---------------------------------------------------------- setup

    def _build_strategies(self) -> dict[str, BaseStrategy]:
        strategies: dict[str, BaseStrategy] = {}
        for product_config in self.config.products.values():
            name = product_config.strategy_name
            if name in strategies:
                continue
            factory = STRATEGY_REGISTRY.get(name)
            if factory is None:
                _LOG.warning("Unknown strategy %r for product config; will be skipped", name)
                continue
            strategies[name] = factory(self.fair_value_engine, self.signal_engine)
        return strategies

    # ---------------------------------------------------------- contract

    # Some Prosperity rounds require a ``bid()`` method on Trader.
    # Keep this stub so contract changes do not break submissions.
    def bid(self) -> int:
        return 15

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        """Entry point called by the Prosperity container.

        Wraps ``_run_body`` in a top-level safety net. An unhandled
        exception in any sub-module would otherwise crash the container
        and lose the iteration entirely.
        """
        try:
            return self._run_body(state)
        except Exception:
            _LOG.exception("Trader.run crashed; returning empty orders")
            if self._reraise_exceptions:
                raise
            return {}, 0, state.traderData

    # ---------------------------------------------------------- body

    def _run_body(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        engine_state = self.state_store.load(state.traderData)
        engine_state.version = self.config.state_version

        snapshots = self.market_data.normalize_state(state)
        results: dict[str, list[Order]] = {}

        for product, snapshot in snapshots.items():
            product_config = self.config.product_config(product)
            if product_config is None:
                results[product] = []
                continue

            strategy = self.strategies.get(product_config.strategy_name)
            if strategy is None:
                results[product] = []
                continue

            memory = engine_state.for_product(product)
            legal_orders = self._step_product(
                product=product,
                snapshot=snapshot,
                memory=memory,
                product_config=product_config,
                strategy=strategy,
                timestamp=state.timestamp,
            )
            results[product] = legal_orders
            self._update_memory(memory, snapshot, product_config.history_length)

        trader_data = self.state_store.save(engine_state)
        conversions = 0
        return results, conversions, trader_data

    # ---------------------------------------------------------- per-product

    def _step_product(
        self,
        *,
        product: str,
        snapshot: NormalizedSnapshot,
        memory: ProductMemory,
        product_config: ProductConfig,
        strategy: BaseStrategy,
        timestamp: int,
    ) -> list[Order]:
        # Observational flow scan — never alters strategy behaviour.
        flow_report = self.flow_analyzer.scan(snapshot, memory)

        context = StrategyContext(
            product=product,
            snapshot=snapshot,
            memory=memory,
            config=product_config,
        )
        intent = strategy.generate_intent(context)
        raw_orders = self.execution_engine.generate_orders(snapshot, intent, product_config)
        raw_orders = self.residual_allocator.augment_orders(
            product=product,
            orders=raw_orders,
            snapshot=snapshot,
            fair_value=intent.fair_value.price,
            position=snapshot.position,
            limit=product_config.position_limit,
            mode=intent.mode,
        )
        legal_orders = self.risk_manager.clip_orders(
            product=product,
            orders=raw_orders,
            current_position=snapshot.position,
            limit=product_config.position_limit,
        )

        event: dict[str, object] = {
            "timestamp": timestamp,
            "product": product,
            "fair_value": round(intent.fair_value.price, 4),
            "method": intent.fair_value.method,
            "position": snapshot.position,
            "mode": intent.mode,
            "orders": [(order.price, order.quantity) for order in legal_orders],
        }
        if flow_report is not None:
            verbosity = self.config.scanner_config.verbosity
            if verbosity >= 2:
                event["flow_report"] = {
                    "net_flow": flow_report.net_flow,
                    "flow_score": flow_report.flow_score,
                    "near_high": flow_report.near_high,
                    "near_low": flow_report.near_low,
                    "flags": list(flow_report.flags),
                    "repeated_sizes": dict(flow_report.repeated_sizes),
                }
            elif verbosity >= 1:
                event["scan_flags"] = list(flow_report.flags)
        self.logger.record(event)
        return legal_orders

    @staticmethod
    def _update_memory(
        memory: ProductMemory, snapshot: NormalizedSnapshot, history_length: int
    ) -> None:
        if history_length <= 0:
            return
        if snapshot.mid is not None:
            bounded_append(memory.recent_mids, float(snapshot.mid), history_length)
        if snapshot.spread is not None:
            bounded_append(memory.recent_spreads, float(snapshot.spread), history_length)

    # ---------------------------------------------------------- helpers

    def reset(self) -> None:
        """Drop any transient in-memory state (diagnostics only)."""
        self.logger = DecisionLogger()

    def engine_state_from(self, trader_data: str | None) -> EngineState:
        """Expose the state store to callers that need to inspect memory."""
        return self.state_store.load(trader_data)
